apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9701
  namespace: load-test-l
data:
  key: "value-9701"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9702
  namespace: load-test-l
data:
  key: "value-9702"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9703
  namespace: load-test-l
data:
  key: "value-9703"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9704
  namespace: load-test-l
data:
  key: "value-9704"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9705
  namespace: load-test-l
data:
  key: "value-9705"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9706
  namespace: load-test-l
data:
  key: "value-9706"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9707
  namespace: load-test-l
data:
  key: "value-9707"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9708
  namespace: load-test-l
data:
  key: "value-9708"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9709
  namespace: load-test-l
data:
  key: "value-9709"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9710
  namespace: load-test-l
data:
  key: "value-9710"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9711
  namespace: load-test-l
data:
  key: "value-9711"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9712
  namespace: load-test-l
data:
  key: "value-9712"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9713
  namespace: load-test-l
data:
  key: "value-9713"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9714
  namespace: load-test-l
data:
  key: "value-9714"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9715
  namespace: load-test-l
data:
  key: "value-9715"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9716
  namespace: load-test-l
data:
  key: "value-9716"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9717
  namespace: load-test-l
data:
  key: "value-9717"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9718
  namespace: load-test-l
data:
  key: "value-9718"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9719
  namespace: load-test-l
data:
  key: "value-9719"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9720
  namespace: load-test-l
data:
  key: "value-9720"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9721
  namespace: load-test-l
data:
  key: "value-9721"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9722
  namespace: load-test-l
data:
  key: "value-9722"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9723
  namespace: load-test-l
data:
  key: "value-9723"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9724
  namespace: load-test-l
data:
  key: "value-9724"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9725
  namespace: load-test-l
data:
  key: "value-9725"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9726
  namespace: load-test-l
data:
  key: "value-9726"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9727
  namespace: load-test-l
data:
  key: "value-9727"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9728
  namespace: load-test-l
data:
  key: "value-9728"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9729
  namespace: load-test-l
data:
  key: "value-9729"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9730
  namespace: load-test-l
data:
  key: "value-9730"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9731
  namespace: load-test-l
data:
  key: "value-9731"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9732
  namespace: load-test-l
data:
  key: "value-9732"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9733
  namespace: load-test-l
data:
  key: "value-9733"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9734
  namespace: load-test-l
data:
  key: "value-9734"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9735
  namespace: load-test-l
data:
  key: "value-9735"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9736
  namespace: load-test-l
data:
  key: "value-9736"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9737
  namespace: load-test-l
data:
  key: "value-9737"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9738
  namespace: load-test-l
data:
  key: "value-9738"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9739
  namespace: load-test-l
data:
  key: "value-9739"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9740
  namespace: load-test-l
data:
  key: "value-9740"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9741
  namespace: load-test-l
data:
  key: "value-9741"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9742
  namespace: load-test-l
data:
  key: "value-9742"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9743
  namespace: load-test-l
data:
  key: "value-9743"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9744
  namespace: load-test-l
data:
  key: "value-9744"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9745
  namespace: load-test-l
data:
  key: "value-9745"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9746
  namespace: load-test-l
data:
  key: "value-9746"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9747
  namespace: load-test-l
data:
  key: "value-9747"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9748
  namespace: load-test-l
data:
  key: "value-9748"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9749
  namespace: load-test-l
data:
  key: "value-9749"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9750
  namespace: load-test-l
data:
  key: "value-9750"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9751
  namespace: load-test-l
data:
  key: "value-9751"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9752
  namespace: load-test-l
data:
  key: "value-9752"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9753
  namespace: load-test-l
data:
  key: "value-9753"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9754
  namespace: load-test-l
data:
  key: "value-9754"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9755
  namespace: load-test-l
data:
  key: "value-9755"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9756
  namespace: load-test-l
data:
  key: "value-9756"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9757
  namespace: load-test-l
data:
  key: "value-9757"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9758
  namespace: load-test-l
data:
  key: "value-9758"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9759
  namespace: load-test-l
data:
  key: "value-9759"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9760
  namespace: load-test-l
data:
  key: "value-9760"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9761
  namespace: load-test-l
data:
  key: "value-9761"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9762
  namespace: load-test-l
data:
  key: "value-9762"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9763
  namespace: load-test-l
data:
  key: "value-9763"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9764
  namespace: load-test-l
data:
  key: "value-9764"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9765
  namespace: load-test-l
data:
  key: "value-9765"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9766
  namespace: load-test-l
data:
  key: "value-9766"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9767
  namespace: load-test-l
data:
  key: "value-9767"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9768
  namespace: load-test-l
data:
  key: "value-9768"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9769
  namespace: load-test-l
data:
  key: "value-9769"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9770
  namespace: load-test-l
data:
  key: "value-9770"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9771
  namespace: load-test-l
data:
  key: "value-9771"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9772
  namespace: load-test-l
data:
  key: "value-9772"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9773
  namespace: load-test-l
data:
  key: "value-9773"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9774
  namespace: load-test-l
data:
  key: "value-9774"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9775
  namespace: load-test-l
data:
  key: "value-9775"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9776
  namespace: load-test-l
data:
  key: "value-9776"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9777
  namespace: load-test-l
data:
  key: "value-9777"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9778
  namespace: load-test-l
data:
  key: "value-9778"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9779
  namespace: load-test-l
data:
  key: "value-9779"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9780
  namespace: load-test-l
data:
  key: "value-9780"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9781
  namespace: load-test-l
data:
  key: "value-9781"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9782
  namespace: load-test-l
data:
  key: "value-9782"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9783
  namespace: load-test-l
data:
  key: "value-9783"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9784
  namespace: load-test-l
data:
  key: "value-9784"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9785
  namespace: load-test-l
data:
  key: "value-9785"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9786
  namespace: load-test-l
data:
  key: "value-9786"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9787
  namespace: load-test-l
data:
  key: "value-9787"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9788
  namespace: load-test-l
data:
  key: "value-9788"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9789
  namespace: load-test-l
data:
  key: "value-9789"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9790
  namespace: load-test-l
data:
  key: "value-9790"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9791
  namespace: load-test-l
data:
  key: "value-9791"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9792
  namespace: load-test-l
data:
  key: "value-9792"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9793
  namespace: load-test-l
data:
  key: "value-9793"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9794
  namespace: load-test-l
data:
  key: "value-9794"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9795
  namespace: load-test-l
data:
  key: "value-9795"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9796
  namespace: load-test-l
data:
  key: "value-9796"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9797
  namespace: load-test-l
data:
  key: "value-9797"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9798
  namespace: load-test-l
data:
  key: "value-9798"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9799
  namespace: load-test-l
data:
  key: "value-9799"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9800
  namespace: load-test-l
data:
  key: "value-9800"
---
