apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7901
  namespace: load-test-l
data:
  key: "value-7901"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7902
  namespace: load-test-l
data:
  key: "value-7902"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7903
  namespace: load-test-l
data:
  key: "value-7903"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7904
  namespace: load-test-l
data:
  key: "value-7904"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7905
  namespace: load-test-l
data:
  key: "value-7905"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7906
  namespace: load-test-l
data:
  key: "value-7906"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7907
  namespace: load-test-l
data:
  key: "value-7907"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7908
  namespace: load-test-l
data:
  key: "value-7908"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7909
  namespace: load-test-l
data:
  key: "value-7909"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7910
  namespace: load-test-l
data:
  key: "value-7910"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7911
  namespace: load-test-l
data:
  key: "value-7911"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7912
  namespace: load-test-l
data:
  key: "value-7912"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7913
  namespace: load-test-l
data:
  key: "value-7913"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7914
  namespace: load-test-l
data:
  key: "value-7914"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7915
  namespace: load-test-l
data:
  key: "value-7915"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7916
  namespace: load-test-l
data:
  key: "value-7916"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7917
  namespace: load-test-l
data:
  key: "value-7917"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7918
  namespace: load-test-l
data:
  key: "value-7918"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7919
  namespace: load-test-l
data:
  key: "value-7919"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7920
  namespace: load-test-l
data:
  key: "value-7920"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7921
  namespace: load-test-l
data:
  key: "value-7921"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7922
  namespace: load-test-l
data:
  key: "value-7922"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7923
  namespace: load-test-l
data:
  key: "value-7923"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7924
  namespace: load-test-l
data:
  key: "value-7924"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7925
  namespace: load-test-l
data:
  key: "value-7925"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7926
  namespace: load-test-l
data:
  key: "value-7926"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7927
  namespace: load-test-l
data:
  key: "value-7927"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7928
  namespace: load-test-l
data:
  key: "value-7928"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7929
  namespace: load-test-l
data:
  key: "value-7929"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7930
  namespace: load-test-l
data:
  key: "value-7930"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7931
  namespace: load-test-l
data:
  key: "value-7931"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7932
  namespace: load-test-l
data:
  key: "value-7932"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7933
  namespace: load-test-l
data:
  key: "value-7933"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7934
  namespace: load-test-l
data:
  key: "value-7934"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7935
  namespace: load-test-l
data:
  key: "value-7935"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7936
  namespace: load-test-l
data:
  key: "value-7936"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7937
  namespace: load-test-l
data:
  key: "value-7937"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7938
  namespace: load-test-l
data:
  key: "value-7938"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7939
  namespace: load-test-l
data:
  key: "value-7939"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7940
  namespace: load-test-l
data:
  key: "value-7940"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7941
  namespace: load-test-l
data:
  key: "value-7941"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7942
  namespace: load-test-l
data:
  key: "value-7942"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7943
  namespace: load-test-l
data:
  key: "value-7943"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7944
  namespace: load-test-l
data:
  key: "value-7944"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7945
  namespace: load-test-l
data:
  key: "value-7945"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7946
  namespace: load-test-l
data:
  key: "value-7946"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7947
  namespace: load-test-l
data:
  key: "value-7947"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7948
  namespace: load-test-l
data:
  key: "value-7948"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7949
  namespace: load-test-l
data:
  key: "value-7949"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7950
  namespace: load-test-l
data:
  key: "value-7950"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7951
  namespace: load-test-l
data:
  key: "value-7951"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7952
  namespace: load-test-l
data:
  key: "value-7952"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7953
  namespace: load-test-l
data:
  key: "value-7953"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7954
  namespace: load-test-l
data:
  key: "value-7954"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7955
  namespace: load-test-l
data:
  key: "value-7955"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7956
  namespace: load-test-l
data:
  key: "value-7956"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7957
  namespace: load-test-l
data:
  key: "value-7957"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7958
  namespace: load-test-l
data:
  key: "value-7958"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7959
  namespace: load-test-l
data:
  key: "value-7959"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7960
  namespace: load-test-l
data:
  key: "value-7960"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7961
  namespace: load-test-l
data:
  key: "value-7961"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7962
  namespace: load-test-l
data:
  key: "value-7962"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7963
  namespace: load-test-l
data:
  key: "value-7963"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7964
  namespace: load-test-l
data:
  key: "value-7964"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7965
  namespace: load-test-l
data:
  key: "value-7965"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7966
  namespace: load-test-l
data:
  key: "value-7966"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7967
  namespace: load-test-l
data:
  key: "value-7967"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7968
  namespace: load-test-l
data:
  key: "value-7968"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7969
  namespace: load-test-l
data:
  key: "value-7969"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7970
  namespace: load-test-l
data:
  key: "value-7970"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7971
  namespace: load-test-l
data:
  key: "value-7971"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7972
  namespace: load-test-l
data:
  key: "value-7972"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7973
  namespace: load-test-l
data:
  key: "value-7973"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7974
  namespace: load-test-l
data:
  key: "value-7974"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7975
  namespace: load-test-l
data:
  key: "value-7975"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7976
  namespace: load-test-l
data:
  key: "value-7976"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7977
  namespace: load-test-l
data:
  key: "value-7977"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7978
  namespace: load-test-l
data:
  key: "value-7978"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7979
  namespace: load-test-l
data:
  key: "value-7979"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7980
  namespace: load-test-l
data:
  key: "value-7980"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7981
  namespace: load-test-l
data:
  key: "value-7981"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7982
  namespace: load-test-l
data:
  key: "value-7982"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7983
  namespace: load-test-l
data:
  key: "value-7983"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7984
  namespace: load-test-l
data:
  key: "value-7984"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7985
  namespace: load-test-l
data:
  key: "value-7985"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7986
  namespace: load-test-l
data:
  key: "value-7986"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7987
  namespace: load-test-l
data:
  key: "value-7987"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7988
  namespace: load-test-l
data:
  key: "value-7988"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7989
  namespace: load-test-l
data:
  key: "value-7989"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7990
  namespace: load-test-l
data:
  key: "value-7990"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7991
  namespace: load-test-l
data:
  key: "value-7991"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7992
  namespace: load-test-l
data:
  key: "value-7992"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7993
  namespace: load-test-l
data:
  key: "value-7993"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7994
  namespace: load-test-l
data:
  key: "value-7994"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7995
  namespace: load-test-l
data:
  key: "value-7995"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7996
  namespace: load-test-l
data:
  key: "value-7996"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7997
  namespace: load-test-l
data:
  key: "value-7997"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7998
  namespace: load-test-l
data:
  key: "value-7998"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7999
  namespace: load-test-l
data:
  key: "value-7999"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8000
  namespace: load-test-l
data:
  key: "value-8000"
---
