apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5001
  namespace: load-test-l
data:
  key: "value-5001"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5002
  namespace: load-test-l
data:
  key: "value-5002"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5003
  namespace: load-test-l
data:
  key: "value-5003"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5004
  namespace: load-test-l
data:
  key: "value-5004"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5005
  namespace: load-test-l
data:
  key: "value-5005"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5006
  namespace: load-test-l
data:
  key: "value-5006"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5007
  namespace: load-test-l
data:
  key: "value-5007"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5008
  namespace: load-test-l
data:
  key: "value-5008"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5009
  namespace: load-test-l
data:
  key: "value-5009"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5010
  namespace: load-test-l
data:
  key: "value-5010"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5011
  namespace: load-test-l
data:
  key: "value-5011"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5012
  namespace: load-test-l
data:
  key: "value-5012"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5013
  namespace: load-test-l
data:
  key: "value-5013"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5014
  namespace: load-test-l
data:
  key: "value-5014"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5015
  namespace: load-test-l
data:
  key: "value-5015"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5016
  namespace: load-test-l
data:
  key: "value-5016"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5017
  namespace: load-test-l
data:
  key: "value-5017"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5018
  namespace: load-test-l
data:
  key: "value-5018"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5019
  namespace: load-test-l
data:
  key: "value-5019"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5020
  namespace: load-test-l
data:
  key: "value-5020"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5021
  namespace: load-test-l
data:
  key: "value-5021"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5022
  namespace: load-test-l
data:
  key: "value-5022"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5023
  namespace: load-test-l
data:
  key: "value-5023"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5024
  namespace: load-test-l
data:
  key: "value-5024"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5025
  namespace: load-test-l
data:
  key: "value-5025"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5026
  namespace: load-test-l
data:
  key: "value-5026"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5027
  namespace: load-test-l
data:
  key: "value-5027"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5028
  namespace: load-test-l
data:
  key: "value-5028"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5029
  namespace: load-test-l
data:
  key: "value-5029"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5030
  namespace: load-test-l
data:
  key: "value-5030"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5031
  namespace: load-test-l
data:
  key: "value-5031"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5032
  namespace: load-test-l
data:
  key: "value-5032"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5033
  namespace: load-test-l
data:
  key: "value-5033"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5034
  namespace: load-test-l
data:
  key: "value-5034"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5035
  namespace: load-test-l
data:
  key: "value-5035"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5036
  namespace: load-test-l
data:
  key: "value-5036"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5037
  namespace: load-test-l
data:
  key: "value-5037"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5038
  namespace: load-test-l
data:
  key: "value-5038"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5039
  namespace: load-test-l
data:
  key: "value-5039"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5040
  namespace: load-test-l
data:
  key: "value-5040"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5041
  namespace: load-test-l
data:
  key: "value-5041"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5042
  namespace: load-test-l
data:
  key: "value-5042"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5043
  namespace: load-test-l
data:
  key: "value-5043"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5044
  namespace: load-test-l
data:
  key: "value-5044"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5045
  namespace: load-test-l
data:
  key: "value-5045"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5046
  namespace: load-test-l
data:
  key: "value-5046"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5047
  namespace: load-test-l
data:
  key: "value-5047"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5048
  namespace: load-test-l
data:
  key: "value-5048"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5049
  namespace: load-test-l
data:
  key: "value-5049"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5050
  namespace: load-test-l
data:
  key: "value-5050"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5051
  namespace: load-test-l
data:
  key: "value-5051"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5052
  namespace: load-test-l
data:
  key: "value-5052"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5053
  namespace: load-test-l
data:
  key: "value-5053"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5054
  namespace: load-test-l
data:
  key: "value-5054"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5055
  namespace: load-test-l
data:
  key: "value-5055"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5056
  namespace: load-test-l
data:
  key: "value-5056"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5057
  namespace: load-test-l
data:
  key: "value-5057"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5058
  namespace: load-test-l
data:
  key: "value-5058"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5059
  namespace: load-test-l
data:
  key: "value-5059"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5060
  namespace: load-test-l
data:
  key: "value-5060"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5061
  namespace: load-test-l
data:
  key: "value-5061"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5062
  namespace: load-test-l
data:
  key: "value-5062"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5063
  namespace: load-test-l
data:
  key: "value-5063"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5064
  namespace: load-test-l
data:
  key: "value-5064"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5065
  namespace: load-test-l
data:
  key: "value-5065"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5066
  namespace: load-test-l
data:
  key: "value-5066"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5067
  namespace: load-test-l
data:
  key: "value-5067"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5068
  namespace: load-test-l
data:
  key: "value-5068"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5069
  namespace: load-test-l
data:
  key: "value-5069"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5070
  namespace: load-test-l
data:
  key: "value-5070"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5071
  namespace: load-test-l
data:
  key: "value-5071"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5072
  namespace: load-test-l
data:
  key: "value-5072"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5073
  namespace: load-test-l
data:
  key: "value-5073"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5074
  namespace: load-test-l
data:
  key: "value-5074"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5075
  namespace: load-test-l
data:
  key: "value-5075"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5076
  namespace: load-test-l
data:
  key: "value-5076"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5077
  namespace: load-test-l
data:
  key: "value-5077"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5078
  namespace: load-test-l
data:
  key: "value-5078"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5079
  namespace: load-test-l
data:
  key: "value-5079"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5080
  namespace: load-test-l
data:
  key: "value-5080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5081
  namespace: load-test-l
data:
  key: "value-5081"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5082
  namespace: load-test-l
data:
  key: "value-5082"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5083
  namespace: load-test-l
data:
  key: "value-5083"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5084
  namespace: load-test-l
data:
  key: "value-5084"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5085
  namespace: load-test-l
data:
  key: "value-5085"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5086
  namespace: load-test-l
data:
  key: "value-5086"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5087
  namespace: load-test-l
data:
  key: "value-5087"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5088
  namespace: load-test-l
data:
  key: "value-5088"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5089
  namespace: load-test-l
data:
  key: "value-5089"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5090
  namespace: load-test-l
data:
  key: "value-5090"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5091
  namespace: load-test-l
data:
  key: "value-5091"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5092
  namespace: load-test-l
data:
  key: "value-5092"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5093
  namespace: load-test-l
data:
  key: "value-5093"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5094
  namespace: load-test-l
data:
  key: "value-5094"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5095
  namespace: load-test-l
data:
  key: "value-5095"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5096
  namespace: load-test-l
data:
  key: "value-5096"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5097
  namespace: load-test-l
data:
  key: "value-5097"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5098
  namespace: load-test-l
data:
  key: "value-5098"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5099
  namespace: load-test-l
data:
  key: "value-5099"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5100
  namespace: load-test-l
data:
  key: "value-5100"
---
