apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2001
  namespace: load-test-l
data:
  key: "value-2001"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2002
  namespace: load-test-l
data:
  key: "value-2002"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2003
  namespace: load-test-l
data:
  key: "value-2003"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2004
  namespace: load-test-l
data:
  key: "value-2004"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2005
  namespace: load-test-l
data:
  key: "value-2005"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2006
  namespace: load-test-l
data:
  key: "value-2006"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2007
  namespace: load-test-l
data:
  key: "value-2007"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2008
  namespace: load-test-l
data:
  key: "value-2008"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2009
  namespace: load-test-l
data:
  key: "value-2009"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2010
  namespace: load-test-l
data:
  key: "value-2010"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2011
  namespace: load-test-l
data:
  key: "value-2011"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2012
  namespace: load-test-l
data:
  key: "value-2012"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2013
  namespace: load-test-l
data:
  key: "value-2013"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2014
  namespace: load-test-l
data:
  key: "value-2014"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2015
  namespace: load-test-l
data:
  key: "value-2015"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2016
  namespace: load-test-l
data:
  key: "value-2016"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2017
  namespace: load-test-l
data:
  key: "value-2017"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2018
  namespace: load-test-l
data:
  key: "value-2018"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2019
  namespace: load-test-l
data:
  key: "value-2019"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2020
  namespace: load-test-l
data:
  key: "value-2020"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2021
  namespace: load-test-l
data:
  key: "value-2021"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2022
  namespace: load-test-l
data:
  key: "value-2022"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2023
  namespace: load-test-l
data:
  key: "value-2023"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2024
  namespace: load-test-l
data:
  key: "value-2024"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2025
  namespace: load-test-l
data:
  key: "value-2025"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2026
  namespace: load-test-l
data:
  key: "value-2026"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2027
  namespace: load-test-l
data:
  key: "value-2027"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2028
  namespace: load-test-l
data:
  key: "value-2028"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2029
  namespace: load-test-l
data:
  key: "value-2029"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2030
  namespace: load-test-l
data:
  key: "value-2030"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2031
  namespace: load-test-l
data:
  key: "value-2031"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2032
  namespace: load-test-l
data:
  key: "value-2032"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2033
  namespace: load-test-l
data:
  key: "value-2033"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2034
  namespace: load-test-l
data:
  key: "value-2034"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2035
  namespace: load-test-l
data:
  key: "value-2035"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2036
  namespace: load-test-l
data:
  key: "value-2036"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2037
  namespace: load-test-l
data:
  key: "value-2037"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2038
  namespace: load-test-l
data:
  key: "value-2038"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2039
  namespace: load-test-l
data:
  key: "value-2039"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2040
  namespace: load-test-l
data:
  key: "value-2040"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2041
  namespace: load-test-l
data:
  key: "value-2041"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2042
  namespace: load-test-l
data:
  key: "value-2042"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2043
  namespace: load-test-l
data:
  key: "value-2043"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2044
  namespace: load-test-l
data:
  key: "value-2044"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2045
  namespace: load-test-l
data:
  key: "value-2045"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2046
  namespace: load-test-l
data:
  key: "value-2046"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2047
  namespace: load-test-l
data:
  key: "value-2047"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2048
  namespace: load-test-l
data:
  key: "value-2048"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2049
  namespace: load-test-l
data:
  key: "value-2049"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2050
  namespace: load-test-l
data:
  key: "value-2050"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2051
  namespace: load-test-l
data:
  key: "value-2051"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2052
  namespace: load-test-l
data:
  key: "value-2052"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2053
  namespace: load-test-l
data:
  key: "value-2053"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2054
  namespace: load-test-l
data:
  key: "value-2054"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2055
  namespace: load-test-l
data:
  key: "value-2055"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2056
  namespace: load-test-l
data:
  key: "value-2056"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2057
  namespace: load-test-l
data:
  key: "value-2057"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2058
  namespace: load-test-l
data:
  key: "value-2058"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2059
  namespace: load-test-l
data:
  key: "value-2059"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2060
  namespace: load-test-l
data:
  key: "value-2060"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2061
  namespace: load-test-l
data:
  key: "value-2061"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2062
  namespace: load-test-l
data:
  key: "value-2062"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2063
  namespace: load-test-l
data:
  key: "value-2063"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2064
  namespace: load-test-l
data:
  key: "value-2064"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2065
  namespace: load-test-l
data:
  key: "value-2065"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2066
  namespace: load-test-l
data:
  key: "value-2066"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2067
  namespace: load-test-l
data:
  key: "value-2067"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2068
  namespace: load-test-l
data:
  key: "value-2068"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2069
  namespace: load-test-l
data:
  key: "value-2069"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2070
  namespace: load-test-l
data:
  key: "value-2070"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2071
  namespace: load-test-l
data:
  key: "value-2071"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2072
  namespace: load-test-l
data:
  key: "value-2072"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2073
  namespace: load-test-l
data:
  key: "value-2073"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2074
  namespace: load-test-l
data:
  key: "value-2074"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2075
  namespace: load-test-l
data:
  key: "value-2075"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2076
  namespace: load-test-l
data:
  key: "value-2076"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2077
  namespace: load-test-l
data:
  key: "value-2077"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2078
  namespace: load-test-l
data:
  key: "value-2078"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2079
  namespace: load-test-l
data:
  key: "value-2079"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2080
  namespace: load-test-l
data:
  key: "value-2080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2081
  namespace: load-test-l
data:
  key: "value-2081"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2082
  namespace: load-test-l
data:
  key: "value-2082"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2083
  namespace: load-test-l
data:
  key: "value-2083"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2084
  namespace: load-test-l
data:
  key: "value-2084"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2085
  namespace: load-test-l
data:
  key: "value-2085"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2086
  namespace: load-test-l
data:
  key: "value-2086"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2087
  namespace: load-test-l
data:
  key: "value-2087"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2088
  namespace: load-test-l
data:
  key: "value-2088"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2089
  namespace: load-test-l
data:
  key: "value-2089"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2090
  namespace: load-test-l
data:
  key: "value-2090"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2091
  namespace: load-test-l
data:
  key: "value-2091"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2092
  namespace: load-test-l
data:
  key: "value-2092"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2093
  namespace: load-test-l
data:
  key: "value-2093"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2094
  namespace: load-test-l
data:
  key: "value-2094"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2095
  namespace: load-test-l
data:
  key: "value-2095"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2096
  namespace: load-test-l
data:
  key: "value-2096"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2097
  namespace: load-test-l
data:
  key: "value-2097"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2098
  namespace: load-test-l
data:
  key: "value-2098"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2099
  namespace: load-test-l
data:
  key: "value-2099"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2100
  namespace: load-test-l
data:
  key: "value-2100"
---
