apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9001
  namespace: load-test-l
data:
  key: "value-9001"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9002
  namespace: load-test-l
data:
  key: "value-9002"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9003
  namespace: load-test-l
data:
  key: "value-9003"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9004
  namespace: load-test-l
data:
  key: "value-9004"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9005
  namespace: load-test-l
data:
  key: "value-9005"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9006
  namespace: load-test-l
data:
  key: "value-9006"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9007
  namespace: load-test-l
data:
  key: "value-9007"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9008
  namespace: load-test-l
data:
  key: "value-9008"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9009
  namespace: load-test-l
data:
  key: "value-9009"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9010
  namespace: load-test-l
data:
  key: "value-9010"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9011
  namespace: load-test-l
data:
  key: "value-9011"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9012
  namespace: load-test-l
data:
  key: "value-9012"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9013
  namespace: load-test-l
data:
  key: "value-9013"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9014
  namespace: load-test-l
data:
  key: "value-9014"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9015
  namespace: load-test-l
data:
  key: "value-9015"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9016
  namespace: load-test-l
data:
  key: "value-9016"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9017
  namespace: load-test-l
data:
  key: "value-9017"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9018
  namespace: load-test-l
data:
  key: "value-9018"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9019
  namespace: load-test-l
data:
  key: "value-9019"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9020
  namespace: load-test-l
data:
  key: "value-9020"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9021
  namespace: load-test-l
data:
  key: "value-9021"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9022
  namespace: load-test-l
data:
  key: "value-9022"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9023
  namespace: load-test-l
data:
  key: "value-9023"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9024
  namespace: load-test-l
data:
  key: "value-9024"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9025
  namespace: load-test-l
data:
  key: "value-9025"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9026
  namespace: load-test-l
data:
  key: "value-9026"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9027
  namespace: load-test-l
data:
  key: "value-9027"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9028
  namespace: load-test-l
data:
  key: "value-9028"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9029
  namespace: load-test-l
data:
  key: "value-9029"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9030
  namespace: load-test-l
data:
  key: "value-9030"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9031
  namespace: load-test-l
data:
  key: "value-9031"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9032
  namespace: load-test-l
data:
  key: "value-9032"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9033
  namespace: load-test-l
data:
  key: "value-9033"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9034
  namespace: load-test-l
data:
  key: "value-9034"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9035
  namespace: load-test-l
data:
  key: "value-9035"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9036
  namespace: load-test-l
data:
  key: "value-9036"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9037
  namespace: load-test-l
data:
  key: "value-9037"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9038
  namespace: load-test-l
data:
  key: "value-9038"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9039
  namespace: load-test-l
data:
  key: "value-9039"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9040
  namespace: load-test-l
data:
  key: "value-9040"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9041
  namespace: load-test-l
data:
  key: "value-9041"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9042
  namespace: load-test-l
data:
  key: "value-9042"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9043
  namespace: load-test-l
data:
  key: "value-9043"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9044
  namespace: load-test-l
data:
  key: "value-9044"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9045
  namespace: load-test-l
data:
  key: "value-9045"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9046
  namespace: load-test-l
data:
  key: "value-9046"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9047
  namespace: load-test-l
data:
  key: "value-9047"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9048
  namespace: load-test-l
data:
  key: "value-9048"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9049
  namespace: load-test-l
data:
  key: "value-9049"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9050
  namespace: load-test-l
data:
  key: "value-9050"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9051
  namespace: load-test-l
data:
  key: "value-9051"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9052
  namespace: load-test-l
data:
  key: "value-9052"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9053
  namespace: load-test-l
data:
  key: "value-9053"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9054
  namespace: load-test-l
data:
  key: "value-9054"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9055
  namespace: load-test-l
data:
  key: "value-9055"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9056
  namespace: load-test-l
data:
  key: "value-9056"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9057
  namespace: load-test-l
data:
  key: "value-9057"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9058
  namespace: load-test-l
data:
  key: "value-9058"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9059
  namespace: load-test-l
data:
  key: "value-9059"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9060
  namespace: load-test-l
data:
  key: "value-9060"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9061
  namespace: load-test-l
data:
  key: "value-9061"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9062
  namespace: load-test-l
data:
  key: "value-9062"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9063
  namespace: load-test-l
data:
  key: "value-9063"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9064
  namespace: load-test-l
data:
  key: "value-9064"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9065
  namespace: load-test-l
data:
  key: "value-9065"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9066
  namespace: load-test-l
data:
  key: "value-9066"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9067
  namespace: load-test-l
data:
  key: "value-9067"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9068
  namespace: load-test-l
data:
  key: "value-9068"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9069
  namespace: load-test-l
data:
  key: "value-9069"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9070
  namespace: load-test-l
data:
  key: "value-9070"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9071
  namespace: load-test-l
data:
  key: "value-9071"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9072
  namespace: load-test-l
data:
  key: "value-9072"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9073
  namespace: load-test-l
data:
  key: "value-9073"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9074
  namespace: load-test-l
data:
  key: "value-9074"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9075
  namespace: load-test-l
data:
  key: "value-9075"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9076
  namespace: load-test-l
data:
  key: "value-9076"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9077
  namespace: load-test-l
data:
  key: "value-9077"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9078
  namespace: load-test-l
data:
  key: "value-9078"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9079
  namespace: load-test-l
data:
  key: "value-9079"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9080
  namespace: load-test-l
data:
  key: "value-9080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9081
  namespace: load-test-l
data:
  key: "value-9081"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9082
  namespace: load-test-l
data:
  key: "value-9082"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9083
  namespace: load-test-l
data:
  key: "value-9083"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9084
  namespace: load-test-l
data:
  key: "value-9084"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9085
  namespace: load-test-l
data:
  key: "value-9085"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9086
  namespace: load-test-l
data:
  key: "value-9086"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9087
  namespace: load-test-l
data:
  key: "value-9087"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9088
  namespace: load-test-l
data:
  key: "value-9088"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9089
  namespace: load-test-l
data:
  key: "value-9089"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9090
  namespace: load-test-l
data:
  key: "value-9090"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9091
  namespace: load-test-l
data:
  key: "value-9091"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9092
  namespace: load-test-l
data:
  key: "value-9092"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9093
  namespace: load-test-l
data:
  key: "value-9093"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9094
  namespace: load-test-l
data:
  key: "value-9094"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9095
  namespace: load-test-l
data:
  key: "value-9095"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9096
  namespace: load-test-l
data:
  key: "value-9096"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9097
  namespace: load-test-l
data:
  key: "value-9097"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9098
  namespace: load-test-l
data:
  key: "value-9098"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9099
  namespace: load-test-l
data:
  key: "value-9099"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9100
  namespace: load-test-l
data:
  key: "value-9100"
---
