apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9801
  namespace: load-test-l
data:
  key: "value-9801"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9802
  namespace: load-test-l
data:
  key: "value-9802"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9803
  namespace: load-test-l
data:
  key: "value-9803"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9804
  namespace: load-test-l
data:
  key: "value-9804"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9805
  namespace: load-test-l
data:
  key: "value-9805"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9806
  namespace: load-test-l
data:
  key: "value-9806"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9807
  namespace: load-test-l
data:
  key: "value-9807"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9808
  namespace: load-test-l
data:
  key: "value-9808"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9809
  namespace: load-test-l
data:
  key: "value-9809"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9810
  namespace: load-test-l
data:
  key: "value-9810"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9811
  namespace: load-test-l
data:
  key: "value-9811"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9812
  namespace: load-test-l
data:
  key: "value-9812"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9813
  namespace: load-test-l
data:
  key: "value-9813"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9814
  namespace: load-test-l
data:
  key: "value-9814"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9815
  namespace: load-test-l
data:
  key: "value-9815"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9816
  namespace: load-test-l
data:
  key: "value-9816"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9817
  namespace: load-test-l
data:
  key: "value-9817"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9818
  namespace: load-test-l
data:
  key: "value-9818"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9819
  namespace: load-test-l
data:
  key: "value-9819"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9820
  namespace: load-test-l
data:
  key: "value-9820"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9821
  namespace: load-test-l
data:
  key: "value-9821"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9822
  namespace: load-test-l
data:
  key: "value-9822"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9823
  namespace: load-test-l
data:
  key: "value-9823"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9824
  namespace: load-test-l
data:
  key: "value-9824"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9825
  namespace: load-test-l
data:
  key: "value-9825"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9826
  namespace: load-test-l
data:
  key: "value-9826"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9827
  namespace: load-test-l
data:
  key: "value-9827"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9828
  namespace: load-test-l
data:
  key: "value-9828"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9829
  namespace: load-test-l
data:
  key: "value-9829"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9830
  namespace: load-test-l
data:
  key: "value-9830"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9831
  namespace: load-test-l
data:
  key: "value-9831"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9832
  namespace: load-test-l
data:
  key: "value-9832"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9833
  namespace: load-test-l
data:
  key: "value-9833"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9834
  namespace: load-test-l
data:
  key: "value-9834"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9835
  namespace: load-test-l
data:
  key: "value-9835"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9836
  namespace: load-test-l
data:
  key: "value-9836"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9837
  namespace: load-test-l
data:
  key: "value-9837"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9838
  namespace: load-test-l
data:
  key: "value-9838"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9839
  namespace: load-test-l
data:
  key: "value-9839"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9840
  namespace: load-test-l
data:
  key: "value-9840"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9841
  namespace: load-test-l
data:
  key: "value-9841"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9842
  namespace: load-test-l
data:
  key: "value-9842"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9843
  namespace: load-test-l
data:
  key: "value-9843"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9844
  namespace: load-test-l
data:
  key: "value-9844"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9845
  namespace: load-test-l
data:
  key: "value-9845"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9846
  namespace: load-test-l
data:
  key: "value-9846"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9847
  namespace: load-test-l
data:
  key: "value-9847"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9848
  namespace: load-test-l
data:
  key: "value-9848"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9849
  namespace: load-test-l
data:
  key: "value-9849"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9850
  namespace: load-test-l
data:
  key: "value-9850"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9851
  namespace: load-test-l
data:
  key: "value-9851"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9852
  namespace: load-test-l
data:
  key: "value-9852"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9853
  namespace: load-test-l
data:
  key: "value-9853"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9854
  namespace: load-test-l
data:
  key: "value-9854"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9855
  namespace: load-test-l
data:
  key: "value-9855"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9856
  namespace: load-test-l
data:
  key: "value-9856"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9857
  namespace: load-test-l
data:
  key: "value-9857"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9858
  namespace: load-test-l
data:
  key: "value-9858"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9859
  namespace: load-test-l
data:
  key: "value-9859"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9860
  namespace: load-test-l
data:
  key: "value-9860"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9861
  namespace: load-test-l
data:
  key: "value-9861"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9862
  namespace: load-test-l
data:
  key: "value-9862"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9863
  namespace: load-test-l
data:
  key: "value-9863"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9864
  namespace: load-test-l
data:
  key: "value-9864"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9865
  namespace: load-test-l
data:
  key: "value-9865"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9866
  namespace: load-test-l
data:
  key: "value-9866"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9867
  namespace: load-test-l
data:
  key: "value-9867"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9868
  namespace: load-test-l
data:
  key: "value-9868"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9869
  namespace: load-test-l
data:
  key: "value-9869"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9870
  namespace: load-test-l
data:
  key: "value-9870"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9871
  namespace: load-test-l
data:
  key: "value-9871"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9872
  namespace: load-test-l
data:
  key: "value-9872"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9873
  namespace: load-test-l
data:
  key: "value-9873"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9874
  namespace: load-test-l
data:
  key: "value-9874"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9875
  namespace: load-test-l
data:
  key: "value-9875"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9876
  namespace: load-test-l
data:
  key: "value-9876"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9877
  namespace: load-test-l
data:
  key: "value-9877"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9878
  namespace: load-test-l
data:
  key: "value-9878"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9879
  namespace: load-test-l
data:
  key: "value-9879"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9880
  namespace: load-test-l
data:
  key: "value-9880"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9881
  namespace: load-test-l
data:
  key: "value-9881"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9882
  namespace: load-test-l
data:
  key: "value-9882"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9883
  namespace: load-test-l
data:
  key: "value-9883"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9884
  namespace: load-test-l
data:
  key: "value-9884"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9885
  namespace: load-test-l
data:
  key: "value-9885"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9886
  namespace: load-test-l
data:
  key: "value-9886"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9887
  namespace: load-test-l
data:
  key: "value-9887"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9888
  namespace: load-test-l
data:
  key: "value-9888"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9889
  namespace: load-test-l
data:
  key: "value-9889"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9890
  namespace: load-test-l
data:
  key: "value-9890"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9891
  namespace: load-test-l
data:
  key: "value-9891"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9892
  namespace: load-test-l
data:
  key: "value-9892"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9893
  namespace: load-test-l
data:
  key: "value-9893"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9894
  namespace: load-test-l
data:
  key: "value-9894"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9895
  namespace: load-test-l
data:
  key: "value-9895"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9896
  namespace: load-test-l
data:
  key: "value-9896"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9897
  namespace: load-test-l
data:
  key: "value-9897"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9898
  namespace: load-test-l
data:
  key: "value-9898"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9899
  namespace: load-test-l
data:
  key: "value-9899"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9900
  namespace: load-test-l
data:
  key: "value-9900"
---
