apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4001
  namespace: load-test-l
data:
  key: "value-4001"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4002
  namespace: load-test-l
data:
  key: "value-4002"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4003
  namespace: load-test-l
data:
  key: "value-4003"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4004
  namespace: load-test-l
data:
  key: "value-4004"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4005
  namespace: load-test-l
data:
  key: "value-4005"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4006
  namespace: load-test-l
data:
  key: "value-4006"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4007
  namespace: load-test-l
data:
  key: "value-4007"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4008
  namespace: load-test-l
data:
  key: "value-4008"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4009
  namespace: load-test-l
data:
  key: "value-4009"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4010
  namespace: load-test-l
data:
  key: "value-4010"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4011
  namespace: load-test-l
data:
  key: "value-4011"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4012
  namespace: load-test-l
data:
  key: "value-4012"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4013
  namespace: load-test-l
data:
  key: "value-4013"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4014
  namespace: load-test-l
data:
  key: "value-4014"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4015
  namespace: load-test-l
data:
  key: "value-4015"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4016
  namespace: load-test-l
data:
  key: "value-4016"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4017
  namespace: load-test-l
data:
  key: "value-4017"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4018
  namespace: load-test-l
data:
  key: "value-4018"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4019
  namespace: load-test-l
data:
  key: "value-4019"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4020
  namespace: load-test-l
data:
  key: "value-4020"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4021
  namespace: load-test-l
data:
  key: "value-4021"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4022
  namespace: load-test-l
data:
  key: "value-4022"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4023
  namespace: load-test-l
data:
  key: "value-4023"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4024
  namespace: load-test-l
data:
  key: "value-4024"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4025
  namespace: load-test-l
data:
  key: "value-4025"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4026
  namespace: load-test-l
data:
  key: "value-4026"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4027
  namespace: load-test-l
data:
  key: "value-4027"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4028
  namespace: load-test-l
data:
  key: "value-4028"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4029
  namespace: load-test-l
data:
  key: "value-4029"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4030
  namespace: load-test-l
data:
  key: "value-4030"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4031
  namespace: load-test-l
data:
  key: "value-4031"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4032
  namespace: load-test-l
data:
  key: "value-4032"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4033
  namespace: load-test-l
data:
  key: "value-4033"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4034
  namespace: load-test-l
data:
  key: "value-4034"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4035
  namespace: load-test-l
data:
  key: "value-4035"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4036
  namespace: load-test-l
data:
  key: "value-4036"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4037
  namespace: load-test-l
data:
  key: "value-4037"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4038
  namespace: load-test-l
data:
  key: "value-4038"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4039
  namespace: load-test-l
data:
  key: "value-4039"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4040
  namespace: load-test-l
data:
  key: "value-4040"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4041
  namespace: load-test-l
data:
  key: "value-4041"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4042
  namespace: load-test-l
data:
  key: "value-4042"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4043
  namespace: load-test-l
data:
  key: "value-4043"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4044
  namespace: load-test-l
data:
  key: "value-4044"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4045
  namespace: load-test-l
data:
  key: "value-4045"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4046
  namespace: load-test-l
data:
  key: "value-4046"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4047
  namespace: load-test-l
data:
  key: "value-4047"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4048
  namespace: load-test-l
data:
  key: "value-4048"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4049
  namespace: load-test-l
data:
  key: "value-4049"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4050
  namespace: load-test-l
data:
  key: "value-4050"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4051
  namespace: load-test-l
data:
  key: "value-4051"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4052
  namespace: load-test-l
data:
  key: "value-4052"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4053
  namespace: load-test-l
data:
  key: "value-4053"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4054
  namespace: load-test-l
data:
  key: "value-4054"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4055
  namespace: load-test-l
data:
  key: "value-4055"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4056
  namespace: load-test-l
data:
  key: "value-4056"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4057
  namespace: load-test-l
data:
  key: "value-4057"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4058
  namespace: load-test-l
data:
  key: "value-4058"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4059
  namespace: load-test-l
data:
  key: "value-4059"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4060
  namespace: load-test-l
data:
  key: "value-4060"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4061
  namespace: load-test-l
data:
  key: "value-4061"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4062
  namespace: load-test-l
data:
  key: "value-4062"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4063
  namespace: load-test-l
data:
  key: "value-4063"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4064
  namespace: load-test-l
data:
  key: "value-4064"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4065
  namespace: load-test-l
data:
  key: "value-4065"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4066
  namespace: load-test-l
data:
  key: "value-4066"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4067
  namespace: load-test-l
data:
  key: "value-4067"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4068
  namespace: load-test-l
data:
  key: "value-4068"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4069
  namespace: load-test-l
data:
  key: "value-4069"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4070
  namespace: load-test-l
data:
  key: "value-4070"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4071
  namespace: load-test-l
data:
  key: "value-4071"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4072
  namespace: load-test-l
data:
  key: "value-4072"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4073
  namespace: load-test-l
data:
  key: "value-4073"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4074
  namespace: load-test-l
data:
  key: "value-4074"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4075
  namespace: load-test-l
data:
  key: "value-4075"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4076
  namespace: load-test-l
data:
  key: "value-4076"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4077
  namespace: load-test-l
data:
  key: "value-4077"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4078
  namespace: load-test-l
data:
  key: "value-4078"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4079
  namespace: load-test-l
data:
  key: "value-4079"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4080
  namespace: load-test-l
data:
  key: "value-4080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4081
  namespace: load-test-l
data:
  key: "value-4081"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4082
  namespace: load-test-l
data:
  key: "value-4082"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4083
  namespace: load-test-l
data:
  key: "value-4083"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4084
  namespace: load-test-l
data:
  key: "value-4084"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4085
  namespace: load-test-l
data:
  key: "value-4085"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4086
  namespace: load-test-l
data:
  key: "value-4086"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4087
  namespace: load-test-l
data:
  key: "value-4087"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4088
  namespace: load-test-l
data:
  key: "value-4088"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4089
  namespace: load-test-l
data:
  key: "value-4089"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4090
  namespace: load-test-l
data:
  key: "value-4090"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4091
  namespace: load-test-l
data:
  key: "value-4091"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4092
  namespace: load-test-l
data:
  key: "value-4092"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4093
  namespace: load-test-l
data:
  key: "value-4093"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4094
  namespace: load-test-l
data:
  key: "value-4094"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4095
  namespace: load-test-l
data:
  key: "value-4095"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4096
  namespace: load-test-l
data:
  key: "value-4096"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4097
  namespace: load-test-l
data:
  key: "value-4097"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4098
  namespace: load-test-l
data:
  key: "value-4098"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4099
  namespace: load-test-l
data:
  key: "value-4099"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4100
  namespace: load-test-l
data:
  key: "value-4100"
---
