apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8901
  namespace: load-test-l
data:
  key: "value-8901"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8902
  namespace: load-test-l
data:
  key: "value-8902"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8903
  namespace: load-test-l
data:
  key: "value-8903"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8904
  namespace: load-test-l
data:
  key: "value-8904"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8905
  namespace: load-test-l
data:
  key: "value-8905"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8906
  namespace: load-test-l
data:
  key: "value-8906"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8907
  namespace: load-test-l
data:
  key: "value-8907"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8908
  namespace: load-test-l
data:
  key: "value-8908"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8909
  namespace: load-test-l
data:
  key: "value-8909"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8910
  namespace: load-test-l
data:
  key: "value-8910"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8911
  namespace: load-test-l
data:
  key: "value-8911"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8912
  namespace: load-test-l
data:
  key: "value-8912"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8913
  namespace: load-test-l
data:
  key: "value-8913"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8914
  namespace: load-test-l
data:
  key: "value-8914"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8915
  namespace: load-test-l
data:
  key: "value-8915"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8916
  namespace: load-test-l
data:
  key: "value-8916"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8917
  namespace: load-test-l
data:
  key: "value-8917"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8918
  namespace: load-test-l
data:
  key: "value-8918"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8919
  namespace: load-test-l
data:
  key: "value-8919"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8920
  namespace: load-test-l
data:
  key: "value-8920"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8921
  namespace: load-test-l
data:
  key: "value-8921"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8922
  namespace: load-test-l
data:
  key: "value-8922"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8923
  namespace: load-test-l
data:
  key: "value-8923"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8924
  namespace: load-test-l
data:
  key: "value-8924"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8925
  namespace: load-test-l
data:
  key: "value-8925"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8926
  namespace: load-test-l
data:
  key: "value-8926"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8927
  namespace: load-test-l
data:
  key: "value-8927"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8928
  namespace: load-test-l
data:
  key: "value-8928"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8929
  namespace: load-test-l
data:
  key: "value-8929"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8930
  namespace: load-test-l
data:
  key: "value-8930"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8931
  namespace: load-test-l
data:
  key: "value-8931"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8932
  namespace: load-test-l
data:
  key: "value-8932"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8933
  namespace: load-test-l
data:
  key: "value-8933"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8934
  namespace: load-test-l
data:
  key: "value-8934"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8935
  namespace: load-test-l
data:
  key: "value-8935"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8936
  namespace: load-test-l
data:
  key: "value-8936"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8937
  namespace: load-test-l
data:
  key: "value-8937"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8938
  namespace: load-test-l
data:
  key: "value-8938"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8939
  namespace: load-test-l
data:
  key: "value-8939"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8940
  namespace: load-test-l
data:
  key: "value-8940"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8941
  namespace: load-test-l
data:
  key: "value-8941"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8942
  namespace: load-test-l
data:
  key: "value-8942"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8943
  namespace: load-test-l
data:
  key: "value-8943"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8944
  namespace: load-test-l
data:
  key: "value-8944"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8945
  namespace: load-test-l
data:
  key: "value-8945"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8946
  namespace: load-test-l
data:
  key: "value-8946"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8947
  namespace: load-test-l
data:
  key: "value-8947"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8948
  namespace: load-test-l
data:
  key: "value-8948"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8949
  namespace: load-test-l
data:
  key: "value-8949"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8950
  namespace: load-test-l
data:
  key: "value-8950"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8951
  namespace: load-test-l
data:
  key: "value-8951"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8952
  namespace: load-test-l
data:
  key: "value-8952"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8953
  namespace: load-test-l
data:
  key: "value-8953"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8954
  namespace: load-test-l
data:
  key: "value-8954"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8955
  namespace: load-test-l
data:
  key: "value-8955"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8956
  namespace: load-test-l
data:
  key: "value-8956"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8957
  namespace: load-test-l
data:
  key: "value-8957"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8958
  namespace: load-test-l
data:
  key: "value-8958"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8959
  namespace: load-test-l
data:
  key: "value-8959"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8960
  namespace: load-test-l
data:
  key: "value-8960"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8961
  namespace: load-test-l
data:
  key: "value-8961"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8962
  namespace: load-test-l
data:
  key: "value-8962"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8963
  namespace: load-test-l
data:
  key: "value-8963"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8964
  namespace: load-test-l
data:
  key: "value-8964"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8965
  namespace: load-test-l
data:
  key: "value-8965"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8966
  namespace: load-test-l
data:
  key: "value-8966"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8967
  namespace: load-test-l
data:
  key: "value-8967"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8968
  namespace: load-test-l
data:
  key: "value-8968"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8969
  namespace: load-test-l
data:
  key: "value-8969"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8970
  namespace: load-test-l
data:
  key: "value-8970"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8971
  namespace: load-test-l
data:
  key: "value-8971"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8972
  namespace: load-test-l
data:
  key: "value-8972"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8973
  namespace: load-test-l
data:
  key: "value-8973"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8974
  namespace: load-test-l
data:
  key: "value-8974"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8975
  namespace: load-test-l
data:
  key: "value-8975"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8976
  namespace: load-test-l
data:
  key: "value-8976"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8977
  namespace: load-test-l
data:
  key: "value-8977"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8978
  namespace: load-test-l
data:
  key: "value-8978"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8979
  namespace: load-test-l
data:
  key: "value-8979"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8980
  namespace: load-test-l
data:
  key: "value-8980"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8981
  namespace: load-test-l
data:
  key: "value-8981"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8982
  namespace: load-test-l
data:
  key: "value-8982"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8983
  namespace: load-test-l
data:
  key: "value-8983"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8984
  namespace: load-test-l
data:
  key: "value-8984"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8985
  namespace: load-test-l
data:
  key: "value-8985"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8986
  namespace: load-test-l
data:
  key: "value-8986"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8987
  namespace: load-test-l
data:
  key: "value-8987"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8988
  namespace: load-test-l
data:
  key: "value-8988"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8989
  namespace: load-test-l
data:
  key: "value-8989"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8990
  namespace: load-test-l
data:
  key: "value-8990"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8991
  namespace: load-test-l
data:
  key: "value-8991"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8992
  namespace: load-test-l
data:
  key: "value-8992"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8993
  namespace: load-test-l
data:
  key: "value-8993"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8994
  namespace: load-test-l
data:
  key: "value-8994"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8995
  namespace: load-test-l
data:
  key: "value-8995"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8996
  namespace: load-test-l
data:
  key: "value-8996"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8997
  namespace: load-test-l
data:
  key: "value-8997"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8998
  namespace: load-test-l
data:
  key: "value-8998"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8999
  namespace: load-test-l
data:
  key: "value-8999"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9000
  namespace: load-test-l
data:
  key: "value-9000"
---
