apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7001
  namespace: load-test-l
data:
  key: "value-7001"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7002
  namespace: load-test-l
data:
  key: "value-7002"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7003
  namespace: load-test-l
data:
  key: "value-7003"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7004
  namespace: load-test-l
data:
  key: "value-7004"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7005
  namespace: load-test-l
data:
  key: "value-7005"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7006
  namespace: load-test-l
data:
  key: "value-7006"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7007
  namespace: load-test-l
data:
  key: "value-7007"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7008
  namespace: load-test-l
data:
  key: "value-7008"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7009
  namespace: load-test-l
data:
  key: "value-7009"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7010
  namespace: load-test-l
data:
  key: "value-7010"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7011
  namespace: load-test-l
data:
  key: "value-7011"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7012
  namespace: load-test-l
data:
  key: "value-7012"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7013
  namespace: load-test-l
data:
  key: "value-7013"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7014
  namespace: load-test-l
data:
  key: "value-7014"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7015
  namespace: load-test-l
data:
  key: "value-7015"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7016
  namespace: load-test-l
data:
  key: "value-7016"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7017
  namespace: load-test-l
data:
  key: "value-7017"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7018
  namespace: load-test-l
data:
  key: "value-7018"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7019
  namespace: load-test-l
data:
  key: "value-7019"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7020
  namespace: load-test-l
data:
  key: "value-7020"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7021
  namespace: load-test-l
data:
  key: "value-7021"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7022
  namespace: load-test-l
data:
  key: "value-7022"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7023
  namespace: load-test-l
data:
  key: "value-7023"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7024
  namespace: load-test-l
data:
  key: "value-7024"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7025
  namespace: load-test-l
data:
  key: "value-7025"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7026
  namespace: load-test-l
data:
  key: "value-7026"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7027
  namespace: load-test-l
data:
  key: "value-7027"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7028
  namespace: load-test-l
data:
  key: "value-7028"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7029
  namespace: load-test-l
data:
  key: "value-7029"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7030
  namespace: load-test-l
data:
  key: "value-7030"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7031
  namespace: load-test-l
data:
  key: "value-7031"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7032
  namespace: load-test-l
data:
  key: "value-7032"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7033
  namespace: load-test-l
data:
  key: "value-7033"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7034
  namespace: load-test-l
data:
  key: "value-7034"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7035
  namespace: load-test-l
data:
  key: "value-7035"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7036
  namespace: load-test-l
data:
  key: "value-7036"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7037
  namespace: load-test-l
data:
  key: "value-7037"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7038
  namespace: load-test-l
data:
  key: "value-7038"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7039
  namespace: load-test-l
data:
  key: "value-7039"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7040
  namespace: load-test-l
data:
  key: "value-7040"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7041
  namespace: load-test-l
data:
  key: "value-7041"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7042
  namespace: load-test-l
data:
  key: "value-7042"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7043
  namespace: load-test-l
data:
  key: "value-7043"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7044
  namespace: load-test-l
data:
  key: "value-7044"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7045
  namespace: load-test-l
data:
  key: "value-7045"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7046
  namespace: load-test-l
data:
  key: "value-7046"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7047
  namespace: load-test-l
data:
  key: "value-7047"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7048
  namespace: load-test-l
data:
  key: "value-7048"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7049
  namespace: load-test-l
data:
  key: "value-7049"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7050
  namespace: load-test-l
data:
  key: "value-7050"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7051
  namespace: load-test-l
data:
  key: "value-7051"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7052
  namespace: load-test-l
data:
  key: "value-7052"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7053
  namespace: load-test-l
data:
  key: "value-7053"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7054
  namespace: load-test-l
data:
  key: "value-7054"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7055
  namespace: load-test-l
data:
  key: "value-7055"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7056
  namespace: load-test-l
data:
  key: "value-7056"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7057
  namespace: load-test-l
data:
  key: "value-7057"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7058
  namespace: load-test-l
data:
  key: "value-7058"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7059
  namespace: load-test-l
data:
  key: "value-7059"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7060
  namespace: load-test-l
data:
  key: "value-7060"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7061
  namespace: load-test-l
data:
  key: "value-7061"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7062
  namespace: load-test-l
data:
  key: "value-7062"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7063
  namespace: load-test-l
data:
  key: "value-7063"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7064
  namespace: load-test-l
data:
  key: "value-7064"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7065
  namespace: load-test-l
data:
  key: "value-7065"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7066
  namespace: load-test-l
data:
  key: "value-7066"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7067
  namespace: load-test-l
data:
  key: "value-7067"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7068
  namespace: load-test-l
data:
  key: "value-7068"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7069
  namespace: load-test-l
data:
  key: "value-7069"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7070
  namespace: load-test-l
data:
  key: "value-7070"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7071
  namespace: load-test-l
data:
  key: "value-7071"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7072
  namespace: load-test-l
data:
  key: "value-7072"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7073
  namespace: load-test-l
data:
  key: "value-7073"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7074
  namespace: load-test-l
data:
  key: "value-7074"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7075
  namespace: load-test-l
data:
  key: "value-7075"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7076
  namespace: load-test-l
data:
  key: "value-7076"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7077
  namespace: load-test-l
data:
  key: "value-7077"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7078
  namespace: load-test-l
data:
  key: "value-7078"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7079
  namespace: load-test-l
data:
  key: "value-7079"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7080
  namespace: load-test-l
data:
  key: "value-7080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7081
  namespace: load-test-l
data:
  key: "value-7081"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7082
  namespace: load-test-l
data:
  key: "value-7082"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7083
  namespace: load-test-l
data:
  key: "value-7083"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7084
  namespace: load-test-l
data:
  key: "value-7084"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7085
  namespace: load-test-l
data:
  key: "value-7085"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7086
  namespace: load-test-l
data:
  key: "value-7086"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7087
  namespace: load-test-l
data:
  key: "value-7087"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7088
  namespace: load-test-l
data:
  key: "value-7088"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7089
  namespace: load-test-l
data:
  key: "value-7089"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7090
  namespace: load-test-l
data:
  key: "value-7090"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7091
  namespace: load-test-l
data:
  key: "value-7091"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7092
  namespace: load-test-l
data:
  key: "value-7092"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7093
  namespace: load-test-l
data:
  key: "value-7093"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7094
  namespace: load-test-l
data:
  key: "value-7094"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7095
  namespace: load-test-l
data:
  key: "value-7095"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7096
  namespace: load-test-l
data:
  key: "value-7096"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7097
  namespace: load-test-l
data:
  key: "value-7097"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7098
  namespace: load-test-l
data:
  key: "value-7098"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7099
  namespace: load-test-l
data:
  key: "value-7099"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7100
  namespace: load-test-l
data:
  key: "value-7100"
---
