apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6001
  namespace: load-test-l
data:
  key: "value-6001"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6002
  namespace: load-test-l
data:
  key: "value-6002"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6003
  namespace: load-test-l
data:
  key: "value-6003"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6004
  namespace: load-test-l
data:
  key: "value-6004"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6005
  namespace: load-test-l
data:
  key: "value-6005"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6006
  namespace: load-test-l
data:
  key: "value-6006"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6007
  namespace: load-test-l
data:
  key: "value-6007"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6008
  namespace: load-test-l
data:
  key: "value-6008"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6009
  namespace: load-test-l
data:
  key: "value-6009"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6010
  namespace: load-test-l
data:
  key: "value-6010"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6011
  namespace: load-test-l
data:
  key: "value-6011"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6012
  namespace: load-test-l
data:
  key: "value-6012"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6013
  namespace: load-test-l
data:
  key: "value-6013"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6014
  namespace: load-test-l
data:
  key: "value-6014"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6015
  namespace: load-test-l
data:
  key: "value-6015"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6016
  namespace: load-test-l
data:
  key: "value-6016"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6017
  namespace: load-test-l
data:
  key: "value-6017"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6018
  namespace: load-test-l
data:
  key: "value-6018"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6019
  namespace: load-test-l
data:
  key: "value-6019"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6020
  namespace: load-test-l
data:
  key: "value-6020"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6021
  namespace: load-test-l
data:
  key: "value-6021"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6022
  namespace: load-test-l
data:
  key: "value-6022"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6023
  namespace: load-test-l
data:
  key: "value-6023"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6024
  namespace: load-test-l
data:
  key: "value-6024"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6025
  namespace: load-test-l
data:
  key: "value-6025"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6026
  namespace: load-test-l
data:
  key: "value-6026"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6027
  namespace: load-test-l
data:
  key: "value-6027"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6028
  namespace: load-test-l
data:
  key: "value-6028"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6029
  namespace: load-test-l
data:
  key: "value-6029"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6030
  namespace: load-test-l
data:
  key: "value-6030"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6031
  namespace: load-test-l
data:
  key: "value-6031"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6032
  namespace: load-test-l
data:
  key: "value-6032"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6033
  namespace: load-test-l
data:
  key: "value-6033"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6034
  namespace: load-test-l
data:
  key: "value-6034"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6035
  namespace: load-test-l
data:
  key: "value-6035"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6036
  namespace: load-test-l
data:
  key: "value-6036"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6037
  namespace: load-test-l
data:
  key: "value-6037"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6038
  namespace: load-test-l
data:
  key: "value-6038"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6039
  namespace: load-test-l
data:
  key: "value-6039"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6040
  namespace: load-test-l
data:
  key: "value-6040"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6041
  namespace: load-test-l
data:
  key: "value-6041"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6042
  namespace: load-test-l
data:
  key: "value-6042"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6043
  namespace: load-test-l
data:
  key: "value-6043"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6044
  namespace: load-test-l
data:
  key: "value-6044"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6045
  namespace: load-test-l
data:
  key: "value-6045"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6046
  namespace: load-test-l
data:
  key: "value-6046"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6047
  namespace: load-test-l
data:
  key: "value-6047"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6048
  namespace: load-test-l
data:
  key: "value-6048"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6049
  namespace: load-test-l
data:
  key: "value-6049"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6050
  namespace: load-test-l
data:
  key: "value-6050"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6051
  namespace: load-test-l
data:
  key: "value-6051"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6052
  namespace: load-test-l
data:
  key: "value-6052"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6053
  namespace: load-test-l
data:
  key: "value-6053"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6054
  namespace: load-test-l
data:
  key: "value-6054"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6055
  namespace: load-test-l
data:
  key: "value-6055"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6056
  namespace: load-test-l
data:
  key: "value-6056"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6057
  namespace: load-test-l
data:
  key: "value-6057"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6058
  namespace: load-test-l
data:
  key: "value-6058"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6059
  namespace: load-test-l
data:
  key: "value-6059"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6060
  namespace: load-test-l
data:
  key: "value-6060"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6061
  namespace: load-test-l
data:
  key: "value-6061"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6062
  namespace: load-test-l
data:
  key: "value-6062"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6063
  namespace: load-test-l
data:
  key: "value-6063"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6064
  namespace: load-test-l
data:
  key: "value-6064"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6065
  namespace: load-test-l
data:
  key: "value-6065"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6066
  namespace: load-test-l
data:
  key: "value-6066"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6067
  namespace: load-test-l
data:
  key: "value-6067"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6068
  namespace: load-test-l
data:
  key: "value-6068"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6069
  namespace: load-test-l
data:
  key: "value-6069"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6070
  namespace: load-test-l
data:
  key: "value-6070"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6071
  namespace: load-test-l
data:
  key: "value-6071"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6072
  namespace: load-test-l
data:
  key: "value-6072"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6073
  namespace: load-test-l
data:
  key: "value-6073"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6074
  namespace: load-test-l
data:
  key: "value-6074"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6075
  namespace: load-test-l
data:
  key: "value-6075"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6076
  namespace: load-test-l
data:
  key: "value-6076"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6077
  namespace: load-test-l
data:
  key: "value-6077"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6078
  namespace: load-test-l
data:
  key: "value-6078"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6079
  namespace: load-test-l
data:
  key: "value-6079"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6080
  namespace: load-test-l
data:
  key: "value-6080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6081
  namespace: load-test-l
data:
  key: "value-6081"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6082
  namespace: load-test-l
data:
  key: "value-6082"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6083
  namespace: load-test-l
data:
  key: "value-6083"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6084
  namespace: load-test-l
data:
  key: "value-6084"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6085
  namespace: load-test-l
data:
  key: "value-6085"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6086
  namespace: load-test-l
data:
  key: "value-6086"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6087
  namespace: load-test-l
data:
  key: "value-6087"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6088
  namespace: load-test-l
data:
  key: "value-6088"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6089
  namespace: load-test-l
data:
  key: "value-6089"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6090
  namespace: load-test-l
data:
  key: "value-6090"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6091
  namespace: load-test-l
data:
  key: "value-6091"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6092
  namespace: load-test-l
data:
  key: "value-6092"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6093
  namespace: load-test-l
data:
  key: "value-6093"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6094
  namespace: load-test-l
data:
  key: "value-6094"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6095
  namespace: load-test-l
data:
  key: "value-6095"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6096
  namespace: load-test-l
data:
  key: "value-6096"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6097
  namespace: load-test-l
data:
  key: "value-6097"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6098
  namespace: load-test-l
data:
  key: "value-6098"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6099
  namespace: load-test-l
data:
  key: "value-6099"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6100
  namespace: load-test-l
data:
  key: "value-6100"
---
