apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1001
  namespace: load-test-l
data:
  key: "value-1001"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1002
  namespace: load-test-l
data:
  key: "value-1002"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1003
  namespace: load-test-l
data:
  key: "value-1003"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1004
  namespace: load-test-l
data:
  key: "value-1004"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1005
  namespace: load-test-l
data:
  key: "value-1005"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1006
  namespace: load-test-l
data:
  key: "value-1006"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1007
  namespace: load-test-l
data:
  key: "value-1007"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1008
  namespace: load-test-l
data:
  key: "value-1008"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1009
  namespace: load-test-l
data:
  key: "value-1009"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1010
  namespace: load-test-l
data:
  key: "value-1010"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1011
  namespace: load-test-l
data:
  key: "value-1011"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1012
  namespace: load-test-l
data:
  key: "value-1012"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1013
  namespace: load-test-l
data:
  key: "value-1013"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1014
  namespace: load-test-l
data:
  key: "value-1014"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1015
  namespace: load-test-l
data:
  key: "value-1015"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1016
  namespace: load-test-l
data:
  key: "value-1016"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1017
  namespace: load-test-l
data:
  key: "value-1017"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1018
  namespace: load-test-l
data:
  key: "value-1018"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1019
  namespace: load-test-l
data:
  key: "value-1019"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1020
  namespace: load-test-l
data:
  key: "value-1020"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1021
  namespace: load-test-l
data:
  key: "value-1021"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1022
  namespace: load-test-l
data:
  key: "value-1022"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1023
  namespace: load-test-l
data:
  key: "value-1023"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1024
  namespace: load-test-l
data:
  key: "value-1024"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1025
  namespace: load-test-l
data:
  key: "value-1025"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1026
  namespace: load-test-l
data:
  key: "value-1026"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1027
  namespace: load-test-l
data:
  key: "value-1027"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1028
  namespace: load-test-l
data:
  key: "value-1028"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1029
  namespace: load-test-l
data:
  key: "value-1029"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1030
  namespace: load-test-l
data:
  key: "value-1030"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1031
  namespace: load-test-l
data:
  key: "value-1031"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1032
  namespace: load-test-l
data:
  key: "value-1032"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1033
  namespace: load-test-l
data:
  key: "value-1033"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1034
  namespace: load-test-l
data:
  key: "value-1034"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1035
  namespace: load-test-l
data:
  key: "value-1035"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1036
  namespace: load-test-l
data:
  key: "value-1036"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1037
  namespace: load-test-l
data:
  key: "value-1037"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1038
  namespace: load-test-l
data:
  key: "value-1038"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1039
  namespace: load-test-l
data:
  key: "value-1039"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1040
  namespace: load-test-l
data:
  key: "value-1040"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1041
  namespace: load-test-l
data:
  key: "value-1041"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1042
  namespace: load-test-l
data:
  key: "value-1042"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1043
  namespace: load-test-l
data:
  key: "value-1043"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1044
  namespace: load-test-l
data:
  key: "value-1044"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1045
  namespace: load-test-l
data:
  key: "value-1045"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1046
  namespace: load-test-l
data:
  key: "value-1046"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1047
  namespace: load-test-l
data:
  key: "value-1047"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1048
  namespace: load-test-l
data:
  key: "value-1048"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1049
  namespace: load-test-l
data:
  key: "value-1049"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1050
  namespace: load-test-l
data:
  key: "value-1050"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1051
  namespace: load-test-l
data:
  key: "value-1051"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1052
  namespace: load-test-l
data:
  key: "value-1052"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1053
  namespace: load-test-l
data:
  key: "value-1053"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1054
  namespace: load-test-l
data:
  key: "value-1054"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1055
  namespace: load-test-l
data:
  key: "value-1055"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1056
  namespace: load-test-l
data:
  key: "value-1056"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1057
  namespace: load-test-l
data:
  key: "value-1057"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1058
  namespace: load-test-l
data:
  key: "value-1058"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1059
  namespace: load-test-l
data:
  key: "value-1059"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1060
  namespace: load-test-l
data:
  key: "value-1060"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1061
  namespace: load-test-l
data:
  key: "value-1061"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1062
  namespace: load-test-l
data:
  key: "value-1062"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1063
  namespace: load-test-l
data:
  key: "value-1063"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1064
  namespace: load-test-l
data:
  key: "value-1064"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1065
  namespace: load-test-l
data:
  key: "value-1065"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1066
  namespace: load-test-l
data:
  key: "value-1066"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1067
  namespace: load-test-l
data:
  key: "value-1067"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1068
  namespace: load-test-l
data:
  key: "value-1068"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1069
  namespace: load-test-l
data:
  key: "value-1069"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1070
  namespace: load-test-l
data:
  key: "value-1070"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1071
  namespace: load-test-l
data:
  key: "value-1071"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1072
  namespace: load-test-l
data:
  key: "value-1072"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1073
  namespace: load-test-l
data:
  key: "value-1073"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1074
  namespace: load-test-l
data:
  key: "value-1074"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1075
  namespace: load-test-l
data:
  key: "value-1075"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1076
  namespace: load-test-l
data:
  key: "value-1076"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1077
  namespace: load-test-l
data:
  key: "value-1077"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1078
  namespace: load-test-l
data:
  key: "value-1078"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1079
  namespace: load-test-l
data:
  key: "value-1079"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1080
  namespace: load-test-l
data:
  key: "value-1080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1081
  namespace: load-test-l
data:
  key: "value-1081"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1082
  namespace: load-test-l
data:
  key: "value-1082"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1083
  namespace: load-test-l
data:
  key: "value-1083"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1084
  namespace: load-test-l
data:
  key: "value-1084"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1085
  namespace: load-test-l
data:
  key: "value-1085"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1086
  namespace: load-test-l
data:
  key: "value-1086"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1087
  namespace: load-test-l
data:
  key: "value-1087"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1088
  namespace: load-test-l
data:
  key: "value-1088"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1089
  namespace: load-test-l
data:
  key: "value-1089"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1090
  namespace: load-test-l
data:
  key: "value-1090"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1091
  namespace: load-test-l
data:
  key: "value-1091"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1092
  namespace: load-test-l
data:
  key: "value-1092"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1093
  namespace: load-test-l
data:
  key: "value-1093"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1094
  namespace: load-test-l
data:
  key: "value-1094"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1095
  namespace: load-test-l
data:
  key: "value-1095"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1096
  namespace: load-test-l
data:
  key: "value-1096"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1097
  namespace: load-test-l
data:
  key: "value-1097"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1098
  namespace: load-test-l
data:
  key: "value-1098"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1099
  namespace: load-test-l
data:
  key: "value-1099"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1100
  namespace: load-test-l
data:
  key: "value-1100"
---
