apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9901
  namespace: load-test-l
data:
  key: "value-9901"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9902
  namespace: load-test-l
data:
  key: "value-9902"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9903
  namespace: load-test-l
data:
  key: "value-9903"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9904
  namespace: load-test-l
data:
  key: "value-9904"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9905
  namespace: load-test-l
data:
  key: "value-9905"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9906
  namespace: load-test-l
data:
  key: "value-9906"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9907
  namespace: load-test-l
data:
  key: "value-9907"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9908
  namespace: load-test-l
data:
  key: "value-9908"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9909
  namespace: load-test-l
data:
  key: "value-9909"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9910
  namespace: load-test-l
data:
  key: "value-9910"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9911
  namespace: load-test-l
data:
  key: "value-9911"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9912
  namespace: load-test-l
data:
  key: "value-9912"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9913
  namespace: load-test-l
data:
  key: "value-9913"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9914
  namespace: load-test-l
data:
  key: "value-9914"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9915
  namespace: load-test-l
data:
  key: "value-9915"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9916
  namespace: load-test-l
data:
  key: "value-9916"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9917
  namespace: load-test-l
data:
  key: "value-9917"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9918
  namespace: load-test-l
data:
  key: "value-9918"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9919
  namespace: load-test-l
data:
  key: "value-9919"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9920
  namespace: load-test-l
data:
  key: "value-9920"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9921
  namespace: load-test-l
data:
  key: "value-9921"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9922
  namespace: load-test-l
data:
  key: "value-9922"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9923
  namespace: load-test-l
data:
  key: "value-9923"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9924
  namespace: load-test-l
data:
  key: "value-9924"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9925
  namespace: load-test-l
data:
  key: "value-9925"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9926
  namespace: load-test-l
data:
  key: "value-9926"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9927
  namespace: load-test-l
data:
  key: "value-9927"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9928
  namespace: load-test-l
data:
  key: "value-9928"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9929
  namespace: load-test-l
data:
  key: "value-9929"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9930
  namespace: load-test-l
data:
  key: "value-9930"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9931
  namespace: load-test-l
data:
  key: "value-9931"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9932
  namespace: load-test-l
data:
  key: "value-9932"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9933
  namespace: load-test-l
data:
  key: "value-9933"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9934
  namespace: load-test-l
data:
  key: "value-9934"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9935
  namespace: load-test-l
data:
  key: "value-9935"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9936
  namespace: load-test-l
data:
  key: "value-9936"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9937
  namespace: load-test-l
data:
  key: "value-9937"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9938
  namespace: load-test-l
data:
  key: "value-9938"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9939
  namespace: load-test-l
data:
  key: "value-9939"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9940
  namespace: load-test-l
data:
  key: "value-9940"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9941
  namespace: load-test-l
data:
  key: "value-9941"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9942
  namespace: load-test-l
data:
  key: "value-9942"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9943
  namespace: load-test-l
data:
  key: "value-9943"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9944
  namespace: load-test-l
data:
  key: "value-9944"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9945
  namespace: load-test-l
data:
  key: "value-9945"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9946
  namespace: load-test-l
data:
  key: "value-9946"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9947
  namespace: load-test-l
data:
  key: "value-9947"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9948
  namespace: load-test-l
data:
  key: "value-9948"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9949
  namespace: load-test-l
data:
  key: "value-9949"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9950
  namespace: load-test-l
data:
  key: "value-9950"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9951
  namespace: load-test-l
data:
  key: "value-9951"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9952
  namespace: load-test-l
data:
  key: "value-9952"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9953
  namespace: load-test-l
data:
  key: "value-9953"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9954
  namespace: load-test-l
data:
  key: "value-9954"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9955
  namespace: load-test-l
data:
  key: "value-9955"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9956
  namespace: load-test-l
data:
  key: "value-9956"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9957
  namespace: load-test-l
data:
  key: "value-9957"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9958
  namespace: load-test-l
data:
  key: "value-9958"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9959
  namespace: load-test-l
data:
  key: "value-9959"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9960
  namespace: load-test-l
data:
  key: "value-9960"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9961
  namespace: load-test-l
data:
  key: "value-9961"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9962
  namespace: load-test-l
data:
  key: "value-9962"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9963
  namespace: load-test-l
data:
  key: "value-9963"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9964
  namespace: load-test-l
data:
  key: "value-9964"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9965
  namespace: load-test-l
data:
  key: "value-9965"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9966
  namespace: load-test-l
data:
  key: "value-9966"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9967
  namespace: load-test-l
data:
  key: "value-9967"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9968
  namespace: load-test-l
data:
  key: "value-9968"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9969
  namespace: load-test-l
data:
  key: "value-9969"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9970
  namespace: load-test-l
data:
  key: "value-9970"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9971
  namespace: load-test-l
data:
  key: "value-9971"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9972
  namespace: load-test-l
data:
  key: "value-9972"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9973
  namespace: load-test-l
data:
  key: "value-9973"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9974
  namespace: load-test-l
data:
  key: "value-9974"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9975
  namespace: load-test-l
data:
  key: "value-9975"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9976
  namespace: load-test-l
data:
  key: "value-9976"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9977
  namespace: load-test-l
data:
  key: "value-9977"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9978
  namespace: load-test-l
data:
  key: "value-9978"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9979
  namespace: load-test-l
data:
  key: "value-9979"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9980
  namespace: load-test-l
data:
  key: "value-9980"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9981
  namespace: load-test-l
data:
  key: "value-9981"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9982
  namespace: load-test-l
data:
  key: "value-9982"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9983
  namespace: load-test-l
data:
  key: "value-9983"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9984
  namespace: load-test-l
data:
  key: "value-9984"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9985
  namespace: load-test-l
data:
  key: "value-9985"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9986
  namespace: load-test-l
data:
  key: "value-9986"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9987
  namespace: load-test-l
data:
  key: "value-9987"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9988
  namespace: load-test-l
data:
  key: "value-9988"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9989
  namespace: load-test-l
data:
  key: "value-9989"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9990
  namespace: load-test-l
data:
  key: "value-9990"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9991
  namespace: load-test-l
data:
  key: "value-9991"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9992
  namespace: load-test-l
data:
  key: "value-9992"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9993
  namespace: load-test-l
data:
  key: "value-9993"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9994
  namespace: load-test-l
data:
  key: "value-9994"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9995
  namespace: load-test-l
data:
  key: "value-9995"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9996
  namespace: load-test-l
data:
  key: "value-9996"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9997
  namespace: load-test-l
data:
  key: "value-9997"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9998
  namespace: load-test-l
data:
  key: "value-9998"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9999
  namespace: load-test-l
data:
  key: "value-9999"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-10000
  namespace: load-test-l
data:
  key: "value-10000"
---
