apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1
  namespace: load-test-l
data:
  key: "value-1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2
  namespace: load-test-l
data:
  key: "value-2"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-3
  namespace: load-test-l
data:
  key: "value-3"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-4
  namespace: load-test-l
data:
  key: "value-4"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-5
  namespace: load-test-l
data:
  key: "value-5"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6
  namespace: load-test-l
data:
  key: "value-6"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7
  namespace: load-test-l
data:
  key: "value-7"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8
  namespace: load-test-l
data:
  key: "value-8"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-9
  namespace: load-test-l
data:
  key: "value-9"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-10
  namespace: load-test-l
data:
  key: "value-10"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-11
  namespace: load-test-l
data:
  key: "value-11"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-12
  namespace: load-test-l
data:
  key: "value-12"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-13
  namespace: load-test-l
data:
  key: "value-13"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-14
  namespace: load-test-l
data:
  key: "value-14"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-15
  namespace: load-test-l
data:
  key: "value-15"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-16
  namespace: load-test-l
data:
  key: "value-16"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-17
  namespace: load-test-l
data:
  key: "value-17"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-18
  namespace: load-test-l
data:
  key: "value-18"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-19
  namespace: load-test-l
data:
  key: "value-19"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-20
  namespace: load-test-l
data:
  key: "value-20"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-21
  namespace: load-test-l
data:
  key: "value-21"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-22
  namespace: load-test-l
data:
  key: "value-22"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-23
  namespace: load-test-l
data:
  key: "value-23"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-24
  namespace: load-test-l
data:
  key: "value-24"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-25
  namespace: load-test-l
data:
  key: "value-25"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-26
  namespace: load-test-l
data:
  key: "value-26"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-27
  namespace: load-test-l
data:
  key: "value-27"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-28
  namespace: load-test-l
data:
  key: "value-28"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-29
  namespace: load-test-l
data:
  key: "value-29"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-30
  namespace: load-test-l
data:
  key: "value-30"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-31
  namespace: load-test-l
data:
  key: "value-31"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-32
  namespace: load-test-l
data:
  key: "value-32"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-33
  namespace: load-test-l
data:
  key: "value-33"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-34
  namespace: load-test-l
data:
  key: "value-34"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-35
  namespace: load-test-l
data:
  key: "value-35"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-36
  namespace: load-test-l
data:
  key: "value-36"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-37
  namespace: load-test-l
data:
  key: "value-37"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-38
  namespace: load-test-l
data:
  key: "value-38"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-39
  namespace: load-test-l
data:
  key: "value-39"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-40
  namespace: load-test-l
data:
  key: "value-40"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-41
  namespace: load-test-l
data:
  key: "value-41"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-42
  namespace: load-test-l
data:
  key: "value-42"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-43
  namespace: load-test-l
data:
  key: "value-43"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-44
  namespace: load-test-l
data:
  key: "value-44"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-45
  namespace: load-test-l
data:
  key: "value-45"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-46
  namespace: load-test-l
data:
  key: "value-46"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-47
  namespace: load-test-l
data:
  key: "value-47"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-48
  namespace: load-test-l
data:
  key: "value-48"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-49
  namespace: load-test-l
data:
  key: "value-49"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-50
  namespace: load-test-l
data:
  key: "value-50"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-51
  namespace: load-test-l
data:
  key: "value-51"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-52
  namespace: load-test-l
data:
  key: "value-52"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-53
  namespace: load-test-l
data:
  key: "value-53"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-54
  namespace: load-test-l
data:
  key: "value-54"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-55
  namespace: load-test-l
data:
  key: "value-55"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-56
  namespace: load-test-l
data:
  key: "value-56"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-57
  namespace: load-test-l
data:
  key: "value-57"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-58
  namespace: load-test-l
data:
  key: "value-58"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-59
  namespace: load-test-l
data:
  key: "value-59"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-60
  namespace: load-test-l
data:
  key: "value-60"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-61
  namespace: load-test-l
data:
  key: "value-61"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-62
  namespace: load-test-l
data:
  key: "value-62"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-63
  namespace: load-test-l
data:
  key: "value-63"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-64
  namespace: load-test-l
data:
  key: "value-64"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-65
  namespace: load-test-l
data:
  key: "value-65"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-66
  namespace: load-test-l
data:
  key: "value-66"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-67
  namespace: load-test-l
data:
  key: "value-67"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-68
  namespace: load-test-l
data:
  key: "value-68"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-69
  namespace: load-test-l
data:
  key: "value-69"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-70
  namespace: load-test-l
data:
  key: "value-70"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-71
  namespace: load-test-l
data:
  key: "value-71"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-72
  namespace: load-test-l
data:
  key: "value-72"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-73
  namespace: load-test-l
data:
  key: "value-73"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-74
  namespace: load-test-l
data:
  key: "value-74"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-75
  namespace: load-test-l
data:
  key: "value-75"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-76
  namespace: load-test-l
data:
  key: "value-76"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-77
  namespace: load-test-l
data:
  key: "value-77"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-78
  namespace: load-test-l
data:
  key: "value-78"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-79
  namespace: load-test-l
data:
  key: "value-79"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-80
  namespace: load-test-l
data:
  key: "value-80"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-81
  namespace: load-test-l
data:
  key: "value-81"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-82
  namespace: load-test-l
data:
  key: "value-82"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-83
  namespace: load-test-l
data:
  key: "value-83"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-84
  namespace: load-test-l
data:
  key: "value-84"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-85
  namespace: load-test-l
data:
  key: "value-85"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-86
  namespace: load-test-l
data:
  key: "value-86"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-87
  namespace: load-test-l
data:
  key: "value-87"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-88
  namespace: load-test-l
data:
  key: "value-88"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-89
  namespace: load-test-l
data:
  key: "value-89"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-90
  namespace: load-test-l
data:
  key: "value-90"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-91
  namespace: load-test-l
data:
  key: "value-91"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-92
  namespace: load-test-l
data:
  key: "value-92"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-93
  namespace: load-test-l
data:
  key: "value-93"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-94
  namespace: load-test-l
data:
  key: "value-94"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-95
  namespace: load-test-l
data:
  key: "value-95"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-96
  namespace: load-test-l
data:
  key: "value-96"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-97
  namespace: load-test-l
data:
  key: "value-97"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-98
  namespace: load-test-l
data:
  key: "value-98"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-99
  namespace: load-test-l
data:
  key: "value-99"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-100
  namespace: load-test-l
data:
  key: "value-100"
---
