apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8001
  namespace: load-test-l
data:
  key: "value-8001"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8002
  namespace: load-test-l
data:
  key: "value-8002"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8003
  namespace: load-test-l
data:
  key: "value-8003"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8004
  namespace: load-test-l
data:
  key: "value-8004"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8005
  namespace: load-test-l
data:
  key: "value-8005"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8006
  namespace: load-test-l
data:
  key: "value-8006"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8007
  namespace: load-test-l
data:
  key: "value-8007"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8008
  namespace: load-test-l
data:
  key: "value-8008"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8009
  namespace: load-test-l
data:
  key: "value-8009"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8010
  namespace: load-test-l
data:
  key: "value-8010"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8011
  namespace: load-test-l
data:
  key: "value-8011"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8012
  namespace: load-test-l
data:
  key: "value-8012"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8013
  namespace: load-test-l
data:
  key: "value-8013"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8014
  namespace: load-test-l
data:
  key: "value-8014"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8015
  namespace: load-test-l
data:
  key: "value-8015"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8016
  namespace: load-test-l
data:
  key: "value-8016"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8017
  namespace: load-test-l
data:
  key: "value-8017"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8018
  namespace: load-test-l
data:
  key: "value-8018"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8019
  namespace: load-test-l
data:
  key: "value-8019"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8020
  namespace: load-test-l
data:
  key: "value-8020"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8021
  namespace: load-test-l
data:
  key: "value-8021"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8022
  namespace: load-test-l
data:
  key: "value-8022"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8023
  namespace: load-test-l
data:
  key: "value-8023"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8024
  namespace: load-test-l
data:
  key: "value-8024"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8025
  namespace: load-test-l
data:
  key: "value-8025"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8026
  namespace: load-test-l
data:
  key: "value-8026"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8027
  namespace: load-test-l
data:
  key: "value-8027"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8028
  namespace: load-test-l
data:
  key: "value-8028"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8029
  namespace: load-test-l
data:
  key: "value-8029"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8030
  namespace: load-test-l
data:
  key: "value-8030"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8031
  namespace: load-test-l
data:
  key: "value-8031"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8032
  namespace: load-test-l
data:
  key: "value-8032"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8033
  namespace: load-test-l
data:
  key: "value-8033"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8034
  namespace: load-test-l
data:
  key: "value-8034"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8035
  namespace: load-test-l
data:
  key: "value-8035"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8036
  namespace: load-test-l
data:
  key: "value-8036"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8037
  namespace: load-test-l
data:
  key: "value-8037"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8038
  namespace: load-test-l
data:
  key: "value-8038"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8039
  namespace: load-test-l
data:
  key: "value-8039"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8040
  namespace: load-test-l
data:
  key: "value-8040"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8041
  namespace: load-test-l
data:
  key: "value-8041"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8042
  namespace: load-test-l
data:
  key: "value-8042"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8043
  namespace: load-test-l
data:
  key: "value-8043"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8044
  namespace: load-test-l
data:
  key: "value-8044"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8045
  namespace: load-test-l
data:
  key: "value-8045"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8046
  namespace: load-test-l
data:
  key: "value-8046"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8047
  namespace: load-test-l
data:
  key: "value-8047"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8048
  namespace: load-test-l
data:
  key: "value-8048"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8049
  namespace: load-test-l
data:
  key: "value-8049"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8050
  namespace: load-test-l
data:
  key: "value-8050"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8051
  namespace: load-test-l
data:
  key: "value-8051"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8052
  namespace: load-test-l
data:
  key: "value-8052"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8053
  namespace: load-test-l
data:
  key: "value-8053"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8054
  namespace: load-test-l
data:
  key: "value-8054"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8055
  namespace: load-test-l
data:
  key: "value-8055"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8056
  namespace: load-test-l
data:
  key: "value-8056"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8057
  namespace: load-test-l
data:
  key: "value-8057"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8058
  namespace: load-test-l
data:
  key: "value-8058"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8059
  namespace: load-test-l
data:
  key: "value-8059"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8060
  namespace: load-test-l
data:
  key: "value-8060"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8061
  namespace: load-test-l
data:
  key: "value-8061"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8062
  namespace: load-test-l
data:
  key: "value-8062"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8063
  namespace: load-test-l
data:
  key: "value-8063"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8064
  namespace: load-test-l
data:
  key: "value-8064"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8065
  namespace: load-test-l
data:
  key: "value-8065"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8066
  namespace: load-test-l
data:
  key: "value-8066"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8067
  namespace: load-test-l
data:
  key: "value-8067"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8068
  namespace: load-test-l
data:
  key: "value-8068"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8069
  namespace: load-test-l
data:
  key: "value-8069"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8070
  namespace: load-test-l
data:
  key: "value-8070"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8071
  namespace: load-test-l
data:
  key: "value-8071"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8072
  namespace: load-test-l
data:
  key: "value-8072"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8073
  namespace: load-test-l
data:
  key: "value-8073"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8074
  namespace: load-test-l
data:
  key: "value-8074"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8075
  namespace: load-test-l
data:
  key: "value-8075"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8076
  namespace: load-test-l
data:
  key: "value-8076"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8077
  namespace: load-test-l
data:
  key: "value-8077"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8078
  namespace: load-test-l
data:
  key: "value-8078"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8079
  namespace: load-test-l
data:
  key: "value-8079"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8080
  namespace: load-test-l
data:
  key: "value-8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8081
  namespace: load-test-l
data:
  key: "value-8081"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8082
  namespace: load-test-l
data:
  key: "value-8082"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8083
  namespace: load-test-l
data:
  key: "value-8083"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8084
  namespace: load-test-l
data:
  key: "value-8084"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8085
  namespace: load-test-l
data:
  key: "value-8085"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8086
  namespace: load-test-l
data:
  key: "value-8086"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8087
  namespace: load-test-l
data:
  key: "value-8087"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8088
  namespace: load-test-l
data:
  key: "value-8088"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8089
  namespace: load-test-l
data:
  key: "value-8089"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8090
  namespace: load-test-l
data:
  key: "value-8090"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8091
  namespace: load-test-l
data:
  key: "value-8091"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8092
  namespace: load-test-l
data:
  key: "value-8092"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8093
  namespace: load-test-l
data:
  key: "value-8093"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8094
  namespace: load-test-l
data:
  key: "value-8094"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8095
  namespace: load-test-l
data:
  key: "value-8095"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8096
  namespace: load-test-l
data:
  key: "value-8096"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8097
  namespace: load-test-l
data:
  key: "value-8097"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8098
  namespace: load-test-l
data:
  key: "value-8098"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8099
  namespace: load-test-l
data:
  key: "value-8099"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-8100
  namespace: load-test-l
data:
  key: "value-8100"
---
