apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6901
  namespace: load-test-l
data:
  key: "value-6901"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6902
  namespace: load-test-l
data:
  key: "value-6902"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6903
  namespace: load-test-l
data:
  key: "value-6903"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6904
  namespace: load-test-l
data:
  key: "value-6904"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6905
  namespace: load-test-l
data:
  key: "value-6905"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6906
  namespace: load-test-l
data:
  key: "value-6906"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6907
  namespace: load-test-l
data:
  key: "value-6907"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6908
  namespace: load-test-l
data:
  key: "value-6908"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6909
  namespace: load-test-l
data:
  key: "value-6909"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6910
  namespace: load-test-l
data:
  key: "value-6910"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6911
  namespace: load-test-l
data:
  key: "value-6911"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6912
  namespace: load-test-l
data:
  key: "value-6912"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6913
  namespace: load-test-l
data:
  key: "value-6913"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6914
  namespace: load-test-l
data:
  key: "value-6914"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6915
  namespace: load-test-l
data:
  key: "value-6915"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6916
  namespace: load-test-l
data:
  key: "value-6916"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6917
  namespace: load-test-l
data:
  key: "value-6917"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6918
  namespace: load-test-l
data:
  key: "value-6918"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6919
  namespace: load-test-l
data:
  key: "value-6919"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6920
  namespace: load-test-l
data:
  key: "value-6920"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6921
  namespace: load-test-l
data:
  key: "value-6921"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6922
  namespace: load-test-l
data:
  key: "value-6922"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6923
  namespace: load-test-l
data:
  key: "value-6923"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6924
  namespace: load-test-l
data:
  key: "value-6924"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6925
  namespace: load-test-l
data:
  key: "value-6925"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6926
  namespace: load-test-l
data:
  key: "value-6926"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6927
  namespace: load-test-l
data:
  key: "value-6927"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6928
  namespace: load-test-l
data:
  key: "value-6928"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6929
  namespace: load-test-l
data:
  key: "value-6929"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6930
  namespace: load-test-l
data:
  key: "value-6930"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6931
  namespace: load-test-l
data:
  key: "value-6931"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6932
  namespace: load-test-l
data:
  key: "value-6932"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6933
  namespace: load-test-l
data:
  key: "value-6933"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6934
  namespace: load-test-l
data:
  key: "value-6934"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6935
  namespace: load-test-l
data:
  key: "value-6935"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6936
  namespace: load-test-l
data:
  key: "value-6936"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6937
  namespace: load-test-l
data:
  key: "value-6937"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6938
  namespace: load-test-l
data:
  key: "value-6938"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6939
  namespace: load-test-l
data:
  key: "value-6939"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6940
  namespace: load-test-l
data:
  key: "value-6940"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6941
  namespace: load-test-l
data:
  key: "value-6941"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6942
  namespace: load-test-l
data:
  key: "value-6942"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6943
  namespace: load-test-l
data:
  key: "value-6943"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6944
  namespace: load-test-l
data:
  key: "value-6944"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6945
  namespace: load-test-l
data:
  key: "value-6945"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6946
  namespace: load-test-l
data:
  key: "value-6946"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6947
  namespace: load-test-l
data:
  key: "value-6947"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6948
  namespace: load-test-l
data:
  key: "value-6948"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6949
  namespace: load-test-l
data:
  key: "value-6949"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6950
  namespace: load-test-l
data:
  key: "value-6950"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6951
  namespace: load-test-l
data:
  key: "value-6951"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6952
  namespace: load-test-l
data:
  key: "value-6952"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6953
  namespace: load-test-l
data:
  key: "value-6953"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6954
  namespace: load-test-l
data:
  key: "value-6954"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6955
  namespace: load-test-l
data:
  key: "value-6955"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6956
  namespace: load-test-l
data:
  key: "value-6956"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6957
  namespace: load-test-l
data:
  key: "value-6957"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6958
  namespace: load-test-l
data:
  key: "value-6958"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6959
  namespace: load-test-l
data:
  key: "value-6959"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6960
  namespace: load-test-l
data:
  key: "value-6960"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6961
  namespace: load-test-l
data:
  key: "value-6961"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6962
  namespace: load-test-l
data:
  key: "value-6962"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6963
  namespace: load-test-l
data:
  key: "value-6963"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6964
  namespace: load-test-l
data:
  key: "value-6964"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6965
  namespace: load-test-l
data:
  key: "value-6965"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6966
  namespace: load-test-l
data:
  key: "value-6966"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6967
  namespace: load-test-l
data:
  key: "value-6967"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6968
  namespace: load-test-l
data:
  key: "value-6968"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6969
  namespace: load-test-l
data:
  key: "value-6969"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6970
  namespace: load-test-l
data:
  key: "value-6970"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6971
  namespace: load-test-l
data:
  key: "value-6971"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6972
  namespace: load-test-l
data:
  key: "value-6972"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6973
  namespace: load-test-l
data:
  key: "value-6973"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6974
  namespace: load-test-l
data:
  key: "value-6974"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6975
  namespace: load-test-l
data:
  key: "value-6975"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6976
  namespace: load-test-l
data:
  key: "value-6976"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6977
  namespace: load-test-l
data:
  key: "value-6977"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6978
  namespace: load-test-l
data:
  key: "value-6978"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6979
  namespace: load-test-l
data:
  key: "value-6979"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6980
  namespace: load-test-l
data:
  key: "value-6980"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6981
  namespace: load-test-l
data:
  key: "value-6981"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6982
  namespace: load-test-l
data:
  key: "value-6982"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6983
  namespace: load-test-l
data:
  key: "value-6983"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6984
  namespace: load-test-l
data:
  key: "value-6984"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6985
  namespace: load-test-l
data:
  key: "value-6985"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6986
  namespace: load-test-l
data:
  key: "value-6986"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6987
  namespace: load-test-l
data:
  key: "value-6987"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6988
  namespace: load-test-l
data:
  key: "value-6988"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6989
  namespace: load-test-l
data:
  key: "value-6989"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6990
  namespace: load-test-l
data:
  key: "value-6990"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6991
  namespace: load-test-l
data:
  key: "value-6991"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6992
  namespace: load-test-l
data:
  key: "value-6992"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6993
  namespace: load-test-l
data:
  key: "value-6993"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6994
  namespace: load-test-l
data:
  key: "value-6994"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6995
  namespace: load-test-l
data:
  key: "value-6995"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6996
  namespace: load-test-l
data:
  key: "value-6996"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6997
  namespace: load-test-l
data:
  key: "value-6997"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6998
  namespace: load-test-l
data:
  key: "value-6998"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-6999
  namespace: load-test-l
data:
  key: "value-6999"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-7000
  namespace: load-test-l
data:
  key: "value-7000"
---
