apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1901
  namespace: load-test-l
data:
  key: "value-1901"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1902
  namespace: load-test-l
data:
  key: "value-1902"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1903
  namespace: load-test-l
data:
  key: "value-1903"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1904
  namespace: load-test-l
data:
  key: "value-1904"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1905
  namespace: load-test-l
data:
  key: "value-1905"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1906
  namespace: load-test-l
data:
  key: "value-1906"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1907
  namespace: load-test-l
data:
  key: "value-1907"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1908
  namespace: load-test-l
data:
  key: "value-1908"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1909
  namespace: load-test-l
data:
  key: "value-1909"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1910
  namespace: load-test-l
data:
  key: "value-1910"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1911
  namespace: load-test-l
data:
  key: "value-1911"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1912
  namespace: load-test-l
data:
  key: "value-1912"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1913
  namespace: load-test-l
data:
  key: "value-1913"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1914
  namespace: load-test-l
data:
  key: "value-1914"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1915
  namespace: load-test-l
data:
  key: "value-1915"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1916
  namespace: load-test-l
data:
  key: "value-1916"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1917
  namespace: load-test-l
data:
  key: "value-1917"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1918
  namespace: load-test-l
data:
  key: "value-1918"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1919
  namespace: load-test-l
data:
  key: "value-1919"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1920
  namespace: load-test-l
data:
  key: "value-1920"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1921
  namespace: load-test-l
data:
  key: "value-1921"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1922
  namespace: load-test-l
data:
  key: "value-1922"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1923
  namespace: load-test-l
data:
  key: "value-1923"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1924
  namespace: load-test-l
data:
  key: "value-1924"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1925
  namespace: load-test-l
data:
  key: "value-1925"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1926
  namespace: load-test-l
data:
  key: "value-1926"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1927
  namespace: load-test-l
data:
  key: "value-1927"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1928
  namespace: load-test-l
data:
  key: "value-1928"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1929
  namespace: load-test-l
data:
  key: "value-1929"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1930
  namespace: load-test-l
data:
  key: "value-1930"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1931
  namespace: load-test-l
data:
  key: "value-1931"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1932
  namespace: load-test-l
data:
  key: "value-1932"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1933
  namespace: load-test-l
data:
  key: "value-1933"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1934
  namespace: load-test-l
data:
  key: "value-1934"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1935
  namespace: load-test-l
data:
  key: "value-1935"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1936
  namespace: load-test-l
data:
  key: "value-1936"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1937
  namespace: load-test-l
data:
  key: "value-1937"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1938
  namespace: load-test-l
data:
  key: "value-1938"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1939
  namespace: load-test-l
data:
  key: "value-1939"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1940
  namespace: load-test-l
data:
  key: "value-1940"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1941
  namespace: load-test-l
data:
  key: "value-1941"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1942
  namespace: load-test-l
data:
  key: "value-1942"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1943
  namespace: load-test-l
data:
  key: "value-1943"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1944
  namespace: load-test-l
data:
  key: "value-1944"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1945
  namespace: load-test-l
data:
  key: "value-1945"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1946
  namespace: load-test-l
data:
  key: "value-1946"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1947
  namespace: load-test-l
data:
  key: "value-1947"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1948
  namespace: load-test-l
data:
  key: "value-1948"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1949
  namespace: load-test-l
data:
  key: "value-1949"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1950
  namespace: load-test-l
data:
  key: "value-1950"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1951
  namespace: load-test-l
data:
  key: "value-1951"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1952
  namespace: load-test-l
data:
  key: "value-1952"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1953
  namespace: load-test-l
data:
  key: "value-1953"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1954
  namespace: load-test-l
data:
  key: "value-1954"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1955
  namespace: load-test-l
data:
  key: "value-1955"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1956
  namespace: load-test-l
data:
  key: "value-1956"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1957
  namespace: load-test-l
data:
  key: "value-1957"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1958
  namespace: load-test-l
data:
  key: "value-1958"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1959
  namespace: load-test-l
data:
  key: "value-1959"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1960
  namespace: load-test-l
data:
  key: "value-1960"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1961
  namespace: load-test-l
data:
  key: "value-1961"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1962
  namespace: load-test-l
data:
  key: "value-1962"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1963
  namespace: load-test-l
data:
  key: "value-1963"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1964
  namespace: load-test-l
data:
  key: "value-1964"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1965
  namespace: load-test-l
data:
  key: "value-1965"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1966
  namespace: load-test-l
data:
  key: "value-1966"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1967
  namespace: load-test-l
data:
  key: "value-1967"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1968
  namespace: load-test-l
data:
  key: "value-1968"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1969
  namespace: load-test-l
data:
  key: "value-1969"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1970
  namespace: load-test-l
data:
  key: "value-1970"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1971
  namespace: load-test-l
data:
  key: "value-1971"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1972
  namespace: load-test-l
data:
  key: "value-1972"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1973
  namespace: load-test-l
data:
  key: "value-1973"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1974
  namespace: load-test-l
data:
  key: "value-1974"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1975
  namespace: load-test-l
data:
  key: "value-1975"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1976
  namespace: load-test-l
data:
  key: "value-1976"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1977
  namespace: load-test-l
data:
  key: "value-1977"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1978
  namespace: load-test-l
data:
  key: "value-1978"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1979
  namespace: load-test-l
data:
  key: "value-1979"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1980
  namespace: load-test-l
data:
  key: "value-1980"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1981
  namespace: load-test-l
data:
  key: "value-1981"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1982
  namespace: load-test-l
data:
  key: "value-1982"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1983
  namespace: load-test-l
data:
  key: "value-1983"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1984
  namespace: load-test-l
data:
  key: "value-1984"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1985
  namespace: load-test-l
data:
  key: "value-1985"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1986
  namespace: load-test-l
data:
  key: "value-1986"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1987
  namespace: load-test-l
data:
  key: "value-1987"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1988
  namespace: load-test-l
data:
  key: "value-1988"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1989
  namespace: load-test-l
data:
  key: "value-1989"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1990
  namespace: load-test-l
data:
  key: "value-1990"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1991
  namespace: load-test-l
data:
  key: "value-1991"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1992
  namespace: load-test-l
data:
  key: "value-1992"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1993
  namespace: load-test-l
data:
  key: "value-1993"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1994
  namespace: load-test-l
data:
  key: "value-1994"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1995
  namespace: load-test-l
data:
  key: "value-1995"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1996
  namespace: load-test-l
data:
  key: "value-1996"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1997
  namespace: load-test-l
data:
  key: "value-1997"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1998
  namespace: load-test-l
data:
  key: "value-1998"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1999
  namespace: load-test-l
data:
  key: "value-1999"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-2000
  namespace: load-test-l
data:
  key: "value-2000"
---
